Repository SU-SWS/stanford_profile, pull requests merged in 2020-11, with the labels that each got.

#322 Updated default content for the paragraph row serializable data
  content/paragraph_row/0427d80b-1f0a-43e1-b902-03d7df3d8523.json
  content/paragraph_row/27047c34-f161-45d4-ab65-c7d7c0e98765.json
  content/paragraph_row/4a607606-12f6-482c-8cd7-a57d64aeff6b.json
  content/paragraph_row/71b78295-dfd1-4eb3-8d20-2013d5b64f69.json
  content/paragraph_row/8f739f14-a899-4880-9c11-5929f0d4ddde.json
  content/paragraph_row/95514879-c3d0-44cc-a8bd-987f547fa1a8.json
  content/paragraph_row/a9a54e9d-e433-408f-be3d-141d3cb3aad6.json
  content/paragraph_row/b9027856-bb49-4c3b-9367-87a4e3731421.json
  content/paragraph_row/ec2d0801-e418-4bec-a1f9-064c349148d7.json
  content/paragraph_row/ed135145-45ed-4955-a1b6-1141bc869568.json
  tests/codeception/acceptance/Paragraphs/ListsCest.php
Labels: size/s

#324 D8CORE-2570 Add intro block above event and news lists
  config/sync/page_manager.page_variant.stanford_events_upcoming-layout_builder-0.yml
  config/sync/page_manager.page_variant.stanford_news_list-layout_builder-0.yml
  config/sync/views.view.su_block_edit_links.yml
  content/block_content/5168834f-3271-4951-bd95-e75340ca5522.json
  content/block_content/f7125c85-197d-4ba2-9f6f-1126bbda0466.json
  tests/codeception/acceptance/Content/EventsCest.php
  tests/codeception/acceptance/Content/NewsCest.php
  tests/codeception/acceptance/Paragraphs/ListsCest.php
Labels: size/s

#325 D8CORE-2960 D8CORE-2961 Update paragraph and field names, with icons
  config/sync/field.field.paragraph.stanford_entity.su_entity_item.yml
  config/sync/field.field.paragraph.stanford_lists.su_list_view.yml
  config/sync/field.field.paragraph_row.node_stanford_page_row.su_page_components.yml
  config/sync/paragraphs.paragraphs_type.stanford_entity.yml
  config/sync/paragraphs.paragraphs_type.stanford_lists.yml
  tests/codeception/functional/Paragraphs/EntityReferenceCest.php
Labels: size/xs

#323 D8CORE-2864 Allow site managers access to contextual links
  config/sync/user.role.site_manager.yml
Labels: size/xs

#326 D8CORE-2957 Updated feedback form link url
  src/Plugin/HelpSection/ProfileHelpSection.php
Labels: size/xs

#331 8.1.20
  CHANGELOG.md
  stanford_profile.info.yml
  tests/codeception/acceptance/AuthenticatedPermissionsCest.php
Labels: patch, size/xs

#332 D8CORE-2495 Changed the link button in minimal html format
  config/sync/editor.editor.stanford_minimal_html.yml
Labels: size/xs

#329 D9 Ready
  composer.json
  config/sync/core.extension.yml
  stanford_profile.info.yml
  tests/codeception/acceptance/AuthenticatedPermissionsCest.php
  tests/codeception/acceptance/Contrib/XmlsitemapCest.php
  tests/codeception/acceptance/LocalFooter/LocalFooterLockupCest.php
  tests/codeception/acceptance/LockupSettings/LockupSettingsCest.php
  tests/src/Kernel/Plugin/InstallTask/RouteRebuilderTest.php
  tests/src/Kernel/Plugin/InstallTask/SiteSettingsTest.php
  tests/src/Kernel/Plugin/InstallTask/UsersTest.php
  tests/src/Kernel/StanfordProfilePermissionsTest.php
  tests/src/Unit/Config/ConfigOverridesTest.php
  tests/src/Unit/EventSubscriber/EventSubscriberTest.php
  tests/src/Unit/Plugin/HelpSection/ProfileConnectSectionTest.php
  tests/src/Unit/Plugin/HelpSection/ProfileHelpSectionTest.php
  tests/src/Unit/Plugin/HelpSection/ProfileResourceSectionTest.php
Labels: patch, size/s

#330 D8CORE-2957 Updated help section language
  src/Plugin/HelpSection/ProfileHelpSection.php
Labels: size/xs

#296 D8CORE-2759 Fix revisions table to show all revisions
  composer.json
  tests/codeception/functional/BasicPage/BasicPageParagraphsCest.php
Labels: size/xs

#334 D8CORE-2878 Add coalesce support for small animated gif fix
  config/sync/imagemagick.settings.yml
Labels: size/xs

#335 D8CORE-3051 Allow paragraph views to display nested taxonomy content
  config/sync/views.view.stanford_events.yml
  config/sync/views.view.stanford_news.yml
  config/sync/views.view.stanford_person.yml
  tests/codeception/acceptance/Paragraphs/ListsCest.php
Labels: size/xs

#337 D8CORE-000 Patch simplesamlphp auth module to prevent unwanted redirect
  composer.json
Labels: size/xs

#338 D8CORE-2325: fixed separator between event dates
  config/sync/core.entity_view_display.node.stanford_event.default.yml
Labels: size/xs
