Repository SU-SWS/stanford_profile, pull requests merged in 2020-09, with the labels that each got.

#282 D8CORE-2535: Changed sort fields on people term pages
  config/sync/views.view.stanford_person_list_terms_first.yml
Labels: size/xs

#284 react columns
  config/sync/core.entity_form_display.node.stanford_page.default.yml
Labels: size/xs

#285 D8CORE-000: Custom theme blocks for custom sites with custom themes.
  stanford_profile.post_update.php
Labels: size/xs

#273 D8CORE-2521: Config updates for embeddables.
  README.md
  config/sync/core.entity_form_display.media.embeddable.default.yml
  config/sync/core.entity_form_display.media.embeddable.media_library.yml
  config/sync/core.entity_view_display.media.embeddable.default.yml
  config/sync/core.entity_view_display.media.embeddable.media_library.yml
  config/sync/field.field.media.embeddable.field_media_embeddable_code.yml
  config/sync/field.field.media.embeddable.field_media_embeddable_oembed.yml
  config/sync/field.storage.media.field_media_embeddable_code.yml
  config/sync/field.storage.media.field_media_embeddable_oembed.yml
  config/sync/media.type.embeddable.yml
  config/sync/user.role.anonymous.yml
  config/sync/user.role.authenticated.yml
  config/sync/user.role.site_builder.yml
  config/sync/user.role.site_developer.yml
  config/sync/user.role.site_editor.yml
  config/sync/user.role.site_manager.yml
  stanford_profile.post_update.php
  tests/codeception/acceptance/Media/MediaCest.php
  tests/codeception/acceptance/Media/MediaPermissionsCest.php
  tests/codeception/acceptance/MediaCest.php
Labels: size/m

#290 HOTFIX-000: Fix up unpublished content
  stanford_profile.post_update.php
Labels: size/xs

#292 added condition to only get untouched nodes
  stanford_profile.post_update.php
Labels: size/xs

#293 8.1.17
  CHANGELOG.md
  stanford_profile.info.yml
  stanford_profile.post_update.php
Labels: patch, size/xs

#294 CAP-52 Import 3 more fields from the API
  config/sync/core.entity_form_display.node.stanford_person.default.yml
  config/sync/core.entity_view_display.node.stanford_person.default.yml
  config/sync/core.entity_view_display.node.stanford_person.teaser.yml
  config/sync/field.field.node.stanford_person.su_person_academic_appt.yml
  config/sync/field.field.node.stanford_person.su_person_admin_appts.yml
  config/sync/field.field.node.stanford_person.su_person_scholarly_interests.yml
  config/sync/field.storage.node.su_person_academic_appt.yml
  config/sync/field.storage.node.su_person_admin_appts.yml
  config/sync/field.storage.node.su_person_scholarly_interests.yml
  config/sync/migrate_plus.migration.su_stanford_person.yml
  tests/codeception/acceptance/Content/PersonCest.php
  tests/codeception/acceptance/LocalFooter/LocalFooterCest.php
Labels: size/s

#298 D8CORE-1200 Additional permission check for deleting home page
  tests/codeception/functional/Users/RolesCest.php
Labels: size/xs

#281 D8 core 2349 wrap person in <a>
  config/sync/views.view.stanford_person.yml
  config/sync/views.view.stanford_person_list_terms_first.yml
Labels: size/s

#300 D8CORE 2498 local footer
  tests/codeception/acceptance/LocalFooter/LocalFooterCest.php
Labels: size/xs

#303 D8CORE-2538 Staff, Faculty, and Students shouldnt see the admin toolbar
  config/sync/user.role.authenticated.yml
  config/sync/user.role.contributor.yml
  config/sync/user.role.site_builder.yml
  config/sync/user.role.site_developer.yml
  config/sync/user.role.site_editor.yml
  config/sync/user.role.site_manager.yml
  tests/codeception/acceptance/Users/RolesCest.php
Labels: size/xs

#302 D8CORE-2531: adding a Contact header to appear when there is any cont…
  config/sync/core.entity_view_display.node.stanford_person.default.yml
Labels: size/xs

#301 D8CORE-2185: matching the person edit to the news edit
  config/sync/views.view.stanford_person.yml
Labels: size/xs

#297 D8CORE-2548: change the pagination counts
  config/sync/views.view.stanford_news.yml
Labels: size/xs

#299 D8CORE-2644: Tests for embeddable media form alters
  tests/codeception/acceptance/Media/MediaFormsCest.php
Labels: size/xs
