Repository SU-SWS/stanford_profile, pull requests merged in 2020-07, with the labels that each got.

#247 D8CORE-2290: moved the cta into details area
  config/sync/core.entity_view_display.node.stanford_event.default.yml
Labels: patch, size/xs

#243 D8CORE-2178, D8CORE-2180, D8CORE-2181: Event updates
  config/sync/core.entity_form_display.node.stanford_news.default.yml
  config/sync/field.field.node.stanford_news.su_news_publishing_date.yml
  config/sync/field.field.node.stanford_news.su_news_topics.yml
  config/sync/views.view.stanford_news.yml
Labels: size/xs

#245 D8CORE-2318: removing the action arrow on list items
  config/sync/views.view.stanford_events.yml
Labels: size/xs

#250 Lock view unpublished to avoid the error in issue #3097251
  composer.json
Labels: size/xs

#252 Update help text for Site URL
  config/sync/field.field.config_pages.stanford_basic_site_settings.su_site_url.yml
Labels: size/xs

#249 D8CORE-2007: removing the span as a wrapper
  config/sync/views.view.stanford_person_terms.yml
Labels: size/xs

#246 D8CORE-2282 D8CORE-2293 Tests for admin toolbar links
  config/sync/config_pages.type.stanford_local_footer.yml
  config/sync/views.view.media.yml
  tests/codeception/acceptance/LocalFooterCest.php
  tests/codeception/acceptance/Users/RolesCest.php
Labels: size/m

#253 D8CORE-2229 Update help section texts
  src/Plugin/HelpSection/ProfileHelpSection.php
  src/Plugin/HelpSection/ProfileResourceSection.php
  tests/src/Unit/Plugin/HelpSection/ProfileResourceSectionTest.php
Labels: size/xs

#251 D8CORE-2317: location changes to events
  config/sync/views.view.stanford_event_series.yml
  config/sync/views.view.stanford_events.yml
Labels: size/l

#258 D8CORE-1828 Enable google tag manager
  composer.json
  config/sync/config_ignore.settings.yml
  config/sync/core.entity_view_mode.node.diff.yml
  config/sync/core.extension.yml
  config/sync/diff.settings.yml
  config/sync/google_tag.settings.yml
  src/Config/ConfigOverrides.php
  stanford_profile.info.yml
  tests/codeception/acceptance/Contrib/NodeRevisionDeleteCest.php
  tests/src/Unit/Config/ConfigOverridesTest.php
Labels: patch, size/s

#263 Removed views_taxonomy_term_name_depth not in use.
  config/sync/core.extension.yml
Labels: size/xs

#260 D8CORE-2155: Added configs for responsive 1:1 image styles
  config/sync/image.style.square_1192.yml
  config/sync/image.style.square_1900.yml
  config/sync/image.style.square_478.yml
  config/sync/image.style.square_956.yml
  config/sync/responsive_image.styles.responsive_1_1.yml
Labels: size/s

#264 DEVOPS-000: Remove field formatter patch
  composer.json
Labels: size/xs

#259 CSD-258 Reset selection when filtered
  config/sync/views.view.content.yml
Labels: size/xs

#240 D8CORE-1241: added tests for authenticated user permissions
  .circleci/config.yml
  tests/codeception/acceptance/AuthenticatedPermissionsCest.php
Labels: size/s

#265 D8CORE-2478 Updated html filter to allow colspan and rowspan.
  config/sync/filter.format.stanford_html.yml
Labels: size/xs
