Repository SU-SWS/stanford_profile, pull requests merged in 2020-06, with the labels that each got.

#226 misc fixes.
  .github/auto-label.json
  .github/workflows/label.yml
  content/node/4b8018dc-49a6-4018-9c54-e8c3e462beee.json
  content/node/6d51339d-ff67-498d-98e9-d8228d36fd51.json
  content/node/72f0069b-f1ec-4122-af73-6aa841faea90.json
  content/node/bc484600-a21a-4497-b9f7-f928474b511c.json
  content/node/d21d84f0-22e7-4596-82cb-9209841a3276.json
  content/node/e18a741f-7d86-492a-a02f-7ca73989ca13.json
Labels: size/xs

#224 Require Drupal Core 8.9
  composer.json
  config/sync/core.extension.yml
  config/sync/sophron.settings.yml
  config/sync/user.role.site_builder.yml
  config/sync/user.role.site_developer.yml
  config/sync/user.role.site_manager.yml
Labels: size/xs

#225 D8CORE-000: Event Importer IDs.
  config/sync/migrate_plus.migration.stanford_events_importer.yml
Labels: size/xs

#229 Use process plugin for the timezone field
  config/sync/migrate_plus.migration.stanford_events_importer.yml
Labels: size/xs

#230 D8CORE-000: Events feedback.
  config/sync/views.view.stanford_events.yml
  config/sync/views.view.stanford_events_past.yml
Labels: size/xs

#227 Added notifications about events and person importer
  stanford_profile.post_update.php
Labels: size/s

#232 Update core.entity_view_display.node.stanford_event.default.yml
  config/sync/core.entity_view_display.node.stanford_event.default.yml
Labels: size/xs

#233 Fix missing event title in views and re-ordered event node fields
  config/sync/core.entity_view_display.node.stanford_event.default.yml
  config/sync/views.view.stanford_events.yml
Labels: size/s

#239 D8CORE-2292: Added in the More news button
  config/sync/views.view.stanford_news.yml
Labels: size/xs

#236 Regenerated and cleaned up migration cron jobs
  config/sync/ultimate_cron.job.stanford_migrate_stanford_events.yml
  config/sync/ultimate_cron.job.stanford_migrate_stanford_events_importer.yml
  config/sync/ultimate_cron.job.stanford_migrate_su_stanford_person.yml
Labels: size/xs

#228 D8CORE-1538 Converting behat tests to codeception tests
  .circleci/config.yml
  tests/behat/assets/documents/test.php
  tests/behat/features/BasicPage.feature
  tests/behat/features/DefaultContent.feature
  tests/behat/features/LocalFooter.feature
  tests/behat/features/Paragraphs/Banner.feature
  tests/behat/features/Paragraphs/Issue2901390.feature
  tests/behat/features/Paragraphs/MediaWithCaption.feature
  tests/behat/features/Paragraphs/WYSIWYG.feature
  tests/behat/features/SystemSiteConfig.feature
  tests/behat/features/TextFormats.feature
  tests/behat/features/Users/DefaultUsers.feature
  tests/behat/features/Users/Roles.feature
  tests/behat/features/contrib/config_readonly.feature
  tests/codeception/acceptance/Content/BasicPageCest.php
  tests/codeception/acceptance/Content/DefaultContentCest.php
  tests/codeception/acceptance/Contrib/ConfigReadonlyCest.php
  tests/codeception/acceptance/LocalFooterCest.php
  tests/codeception/acceptance/Paragraphs/BannerCest.php
  tests/codeception/acceptance/Paragraphs/Issue2901390Cest.php
  tests/codeception/acceptance/Paragraphs/MediaWithCaptionCest.php
  tests/codeception/acceptance/SystemSiteConfigCest.php
  tests/codeception/acceptance/TextFormatsCest.php
  tests/codeception/acceptance/Users/DefaultUsersCest.php
  tests/codeception/acceptance/Users/RolesCest.php
  tests/codeception/functional/Paragraphs/WYSIWYG.html
  tests/codeception/functional/Paragraphs/WYSIWYGCest.php
  tests/codeception/functional/Paragraphs/logo.jpg
  tests/codeception/functional/Paragraphs/test.txt
Labels: size/l

#238 D8CORE-1930: Changing the multirow gutters and removing the fixed widths
  modules/stanford_profile_styles/dist/css/stanford_profile_styles.layout.stanford_page.full.css
  modules/stanford_profile_styles/dist/css/stanford_profile_styles.node.stanford_page.css
  modules/stanford_profile_styles/dist/css/stanford_profile_styles.react_paragraphs.css
  modules/stanford_profile_styles/lib/scss/node-types/stanford_page.layout.full-width.scss
  modules/stanford_profile_styles/lib/scss/node-types/stanford_page.scss
  modules/stanford_profile_styles/lib/scss/paragraph-types/react_paragraphs/_multirow.scss
Labels: size/s

#237 D8CORE-2205 Configure config ignore to allow for custom theme enabling
  composer.json
  config/sync/config_ignore.settings.yml
  config/sync/core.extension.yml
  src/Config/ConfigOverrides.php
  stanford_profile.profile
  stanford_profile.services.yml
  tests/codeception/acceptance/SubThemeCest.php
  tests/src/Unit/Config/ConfigOverridesTest.php
Labels: size/s

#241 D8CORE-2049: change telephone to contact
  config/sync/core.entity_view_display.node.stanford_person.default.yml
Labels: size/xs

#242 D8CORE-2099: Added required fields and default image for profile.
  config/sync/field.field.node.stanford_person.su_person_first_name.yml
  config/sync/field.field.node.stanford_person.su_person_last_name.yml
  config/sync/field.field.node.stanford_person.su_person_photo.yml
  config/sync/field.field.node.stanford_person.su_person_short_title.yml
  config/sync/field.storage.node.su_person_first_name.yml
  config/sync/field.storage.node.su_person_full_title.yml
  config/sync/field.storage.node.su_person_last_name.yml
  config/sync/field.storage.node.su_person_photo.yml
Labels: size/xs

#244 D8CORE-1722: Basically remove everything code related from this profile.
  composer.json
  config/sync/core.extension.yml
  modules/stanford_paragraph_card/stanford_paragraph_card.info.yml
  modules/stanford_paragraph_card/stanford_paragraph_card.module
  modules/stanford_paragraph_card/tests/behat/features/Card.feature
  modules/stanford_profile_drush/drush.services.yml
  modules/stanford_profile_drush/src/Commands/StanfordProfileCommands.php
  modules/stanford_profile_drush/stanford_profile_drush.info.yml
  modules/stanford_profile_drush/tests/src/Kernel/Commands/StanfordProfileCommandsTest.php
  modules/stanford_profile_styles/.browserslistrc
  modules/stanford_profile_styles/.nvmrc
  modules/stanford_profile_styles/README.md
  modules/stanford_profile_styles/assets/svg/caret-right.svg
  modules/stanford_profile_styles/dist/css/stanford_profile_styles.admin.node_form.css
  modules/stanford_profile_styles/dist/css/stanford_profile_styles.ckeditor.css
  modules/stanford_profile_styles/dist/css/stanford_profile_styles.css
  modules/stanford_profile_styles/dist/css/stanford_profile_styles.field_widgets.css
  modules/stanford_profile_styles/dist/css/stanford_profile_styles.layout.stanford_page.full.css
  modules/stanford_profile_styles/dist/css/stanford_profile_styles.node.stanford_page.css
  modules/stanford_profile_styles/dist/css/stanford_profile_styles.paragraph.spacer.css
  modules/stanford_profile_styles/dist/css/stanford_profile_styles.paragraph.wysiwyg.css
  modules/stanford_profile_styles/dist/css/stanford_profile_styles.react_paragraphs.css
  modules/stanford_profile_styles/lib/README.md
  modules/stanford_profile_styles/lib/assets/img/.gitkeep
  modules/stanford_profile_styles/lib/assets/svg/.gitkeep
  modules/stanford_profile_styles/lib/scss/_config.scss
  modules/stanford_profile_styles/lib/scss/admin/_node_form_stanford_page.scss
  modules/stanford_profile_styles/lib/scss/admin/ckeditor.scss
  modules/stanford_profile_styles/lib/scss/admin/field_widgets.scss
  modules/stanford_profile_styles/lib/scss/admin/node_forms.scss
  modules/stanford_profile_styles/lib/scss/node-types/stanford_page.layout.full-width.scss
  modules/stanford_profile_styles/lib/scss/node-types/stanford_page.scss
  modules/stanford_profile_styles/lib/scss/paragraph-types/react_paragraphs/_multirow.scss
  modules/stanford_profile_styles/lib/scss/paragraph-types/react_paragraphs/index.scss
  modules/stanford_profile_styles/lib/scss/paragraph-types/spacer/_spacer.scss
  modules/stanford_profile_styles/lib/scss/paragraph-types/spacer/index.scss
  modules/stanford_profile_styles/lib/scss/paragraph-types/wysiwyg/_buttons.scss
  modules/stanford_profile_styles/lib/scss/paragraph-types/wysiwyg/_headings.scss
  modules/stanford_profile_styles/lib/scss/paragraph-types/wysiwyg/_lists.scss
  modules/stanford_profile_styles/lib/scss/paragraph-types/wysiwyg/_paragraph.scss
  modules/stanford_profile_styles/lib/scss/paragraph-types/wysiwyg/_table.scss
  modules/stanford_profile_styles/lib/scss/paragraph-types/wysiwyg/_wysiwyg.scss
  modules/stanford_profile_styles/lib/scss/paragraph-types/wysiwyg/index.scss
  modules/stanford_profile_styles/lib/scss/stanford_profile_styles.scss
  modules/stanford_profile_styles/package-lock.json
  modules/stanford_profile_styles/package.json
  modules/stanford_profile_styles/stanford_profile_styles.info.yml
  modules/stanford_profile_styles/stanford_profile_styles.libraries.yml
  modules/stanford_profile_styles/stanford_profile_styles.module
  modules/stanford_profile_styles/tests/behat/features/README.md
  modules/stanford_profile_styles/tests/behat/media/README.md
  modules/stanford_profile_styles/webpack.config.js
  stanford_profile.info.yml
  stanford_profile.profile
  tests/codeception/acceptance/Users/RolesCest.php
Labels: size/xl
