Repository SU-SWS/stanford_profile, pull requests merged in 2020-08, with the labels that each got.

#220 D8CORE-1472: Config Page for Lockup Configuration.
  config/sync/config_pages.type.lockup_settings.yml
  config/sync/core.entity_form_display.config_pages.lockup_settings.default.yml
  config/sync/core.entity_view_display.config_pages.lockup_settings.default.yml
  config/sync/field.field.config_pages.lockup_settings.su_line_1.yml
  config/sync/field.field.config_pages.lockup_settings.su_line_2.yml
  config/sync/field.field.config_pages.lockup_settings.su_line_3.yml
  config/sync/field.field.config_pages.lockup_settings.su_line_4.yml
  config/sync/field.field.config_pages.lockup_settings.su_line_5.yml
  config/sync/field.field.config_pages.lockup_settings.su_lockup_enabled.yml
  config/sync/field.field.config_pages.lockup_settings.su_lockup_options.yml
  config/sync/field.field.config_pages.lockup_settings.su_upload_logo_image.yml
  config/sync/field.field.config_pages.lockup_settings.su_use_theme_logo.yml
  config/sync/field.storage.config_pages.su_line_1.yml
  config/sync/field.storage.config_pages.su_line_2.yml
  config/sync/field.storage.config_pages.su_line_3.yml
  config/sync/field.storage.config_pages.su_line_4.yml
  config/sync/field.storage.config_pages.su_line_5.yml
  config/sync/field.storage.config_pages.su_lockup_enabled.yml
  config/sync/field.storage.config_pages.su_lockup_options.yml
  config/sync/field.storage.config_pages.su_upload_logo_image.yml
  config/sync/field.storage.config_pages.su_use_theme_logo.yml
  config/sync/stanford_basic.settings.yml
  config/sync/user.role.site_manager.yml
  tests/codeception/acceptance/LockupSettings/LockupSettingsCest.php
  tests/codeception/acceptance/LockupSettings/LockupSettingsPermsCest.php
  tests/codeception/acceptance/LockupSettings/logo.jpg
Labels: size/l

#266 Added missing extlink config
  config/sync/core.extension.yml
  config/sync/extlink.settings.yml
Labels: size/xs

#268 8.1.15
  .circleci/config.yml
  CHANGELOG.md
  composer.json
  config/sync/config_ignore.settings.yml
  config/sync/config_pages.type.lockup_settings.yml
  config/sync/core.entity_form_display.config_pages.lockup_settings.default.yml
  config/sync/core.entity_view_display.config_pages.lockup_settings.default.yml
  config/sync/core.entity_view_mode.node.diff.yml
  config/sync/core.extension.yml
  config/sync/diff.settings.yml
  config/sync/field.field.config_pages.lockup_settings.su_line_1.yml
  config/sync/field.field.config_pages.lockup_settings.su_line_2.yml
  config/sync/field.field.config_pages.lockup_settings.su_line_3.yml
  config/sync/field.field.config_pages.lockup_settings.su_line_4.yml
  config/sync/field.field.config_pages.lockup_settings.su_line_5.yml
  config/sync/field.field.config_pages.lockup_settings.su_lockup_enabled.yml
  config/sync/field.field.config_pages.lockup_settings.su_lockup_options.yml
  config/sync/field.field.config_pages.lockup_settings.su_upload_logo_image.yml
  config/sync/field.field.config_pages.lockup_settings.su_use_theme_logo.yml
  config/sync/field.storage.config_pages.su_line_1.yml
  config/sync/field.storage.config_pages.su_line_2.yml
  config/sync/field.storage.config_pages.su_line_3.yml
  config/sync/field.storage.config_pages.su_line_4.yml
  config/sync/field.storage.config_pages.su_line_5.yml
  config/sync/field.storage.config_pages.su_lockup_enabled.yml
  config/sync/field.storage.config_pages.su_lockup_options.yml
  config/sync/field.storage.config_pages.su_upload_logo_image.yml
  config/sync/field.storage.config_pages.su_use_theme_logo.yml
  config/sync/filter.format.stanford_html.yml
  config/sync/google_tag.settings.yml
  config/sync/image.style.square_1192.yml
  config/sync/image.style.square_1900.yml
  config/sync/image.style.square_478.yml
  config/sync/image.style.square_956.yml
  config/sync/responsive_image.styles.responsive_1_1.yml
  config/sync/stanford_basic.settings.yml
  config/sync/user.role.site_manager.yml
  config/sync/views.view.content.yml
  src/Config/ConfigOverrides.php
  stanford_profile.info.yml
  tests/codeception/acceptance/AuthenticatedPermissionsCest.php
  tests/codeception/acceptance/Contrib/NodeRevisionDeleteCest.php
  tests/codeception/acceptance/LockupSettings/LockupSettingsCest.php
  tests/codeception/acceptance/LockupSettings/LockupSettingsPermsCest.php
  tests/codeception/acceptance/LockupSettings/logo.jpg
  tests/src/Unit/Config/ConfigOverridesTest.php
Labels: patch, size/xs

#271 DEVOPS-000: Update paragraphs lang patch
  composer.json
Labels: size/xs

#261 D8CORE-2201: adding extlink dependency
  composer.json
  config/sync/core.extension.yml
  config/sync/extlink.settings.yml
  config/sync/taxonomy_menu.taxonomy_menu.event_types_menu.yml
  config/sync/taxonomy_menu.taxonomy_menu.person_type_menu.yml
  config/sync/taxonomy_menu.taxonomy_menu.topics_taxonomy_menu.yml
  stanford_profile.info.yml
  tests/codeception/functional/Contrib/ExtLinkCest.php
  tests/codeception/functional/Paragraphs/WYSIWYGCest.php
Labels: patch, size/s

#272 DEVGUIDE-000 Added html pre tag to allowed html tags.
  config/sync/filter.format.stanford_html.yml
Labels: patch, size/xs

#278 D8CORE-2591: Allow lockup option M
  config/sync/field.storage.config_pages.su_lockup_options.yml
  tests/codeception/acceptance/LockupSettings/LockupSettingsCest.php
Labels: size/xs
