Repository SU-SWS/stanford_profile, pull requests merged in 2021-04, with the labels that each got.

#396 D8CORE-4020: fixup on config
  config/sync/core.entity_view_display.node.stanford_publication.stanford_card.yml
Labels: size/xs

#394 D8CORE-3953 Replace "whitelist" with "allowed" for stanford_ssp
  config/sync/config_pages.type.stanford_saml.yml
  config/sync/stanford_ssp.settings.yml
Labels: size/xs

#397 D8CORE-4033: updated view config to allow filtering past events lists
  config/sync/views.view.stanford_events.yml
Labels: size/xs

#357 D8CORE-2766: config change for global message form
  config/sync/field.field.config_pages.stanford_global_message.su_global_msg_message.yml
Labels: size/xs

#395 D8CORE-2572 Added and configured content_lock to prevent simultaneous edits
  composer.json
  config/sync/content_lock.settings.yml
  config/sync/content_lock_timeout.settings.yml
  config/sync/core.entity_view_display.node.stanford_publication.teaser.yml
  config/sync/core.extension.yml
  config/sync/system.action.media_break_lock_action.yml
  config/sync/system.action.node_break_lock_action.yml
  config/sync/ultimate_cron.job.content_lock_timeout_cron.yml
  config/sync/user.role.contributor.yml
  config/sync/user.role.site_builder.yml
  config/sync/user.role.site_developer.yml
  config/sync/user.role.site_editor.yml
  config/sync/user.role.site_manager.yml
  config/sync/views.view.locked_content.yml
Labels: size/m

#388 D8CORE-3254: basic pages plus
  config/sync/core.entity_form_display.node.stanford_page.default.yml
  config/sync/core.entity_view_display.node.stanford_event_series.stanford_card.yml
  config/sync/core.entity_view_display.node.stanford_event_series.teaser.yml
  config/sync/core.entity_view_display.node.stanford_page.default.yml
  config/sync/core.entity_view_display.node.stanford_page.stanford_card.yml
  config/sync/core.entity_view_display.node.stanford_person.teaser.yml
  config/sync/core.entity_view_display.node.stanford_publication.teaser.yml
  config/sync/core.entity_view_display.paragraph.stanford_banner.variant_1.yml
  config/sync/core.extension.yml
  config/sync/ds.field.basic_page_type_content_url.yml
  config/sync/field.field.node.stanford_page.su_basic_page_type.yml
  config/sync/field.field.node.stanford_page.su_page_description.yml
  config/sync/field.field.node.stanford_page.su_page_image.yml
  config/sync/field.field.paragraph.stanford_entity.su_entity_item.yml
  config/sync/field.field.paragraph.stanford_lists.su_list_view.yml
  config/sync/field.storage.node.su_basic_page_type.yml
  config/sync/field.storage.node.su_page_description.yml
  config/sync/field.storage.node.su_page_image.yml
  config/sync/metatag.metatag_defaults.node.yml
  config/sync/migrate_plus.migration.su_stanford_person.yml
  config/sync/taxonomy.vocabulary.basic_page_types.yml
  config/sync/user.role.site_builder.yml
  config/sync/user.role.site_developer.yml
  config/sync/user.role.site_editor.yml
  config/sync/user.role.site_manager.yml
  config/sync/views.view.stanford_basic_pages.yml
  tests/codeception/acceptance/Content/BasicPageCest.php
  tests/codeception/acceptance/Paragraphs/ListsCest.php
Labels: size/l

#401 D8CORE-3480 Disallow image gallery media in the wysiwyg.
  config/sync/filter.format.stanford_html.yml
Labels: size/xs

#400 8.2.5
  CHANGELOG.md
  config/sync/core.entity_form_display.node.stanford_page.default.yml
  config/sync/core.entity_view_display.node.stanford_page.default.yml
  config/sync/filter.format.stanford_html.yml
  config/sync/node.type.stanford_publication.yml
  config/sync/views.view.stanford_basic_pages.yml
  stanford_profile.info.yml
  tests/codeception/acceptance/Content/BasicPageCest.php
Labels: patch, size/xs

#402 D8CORE-4068 Allow publication authors to have only one name part
  config/sync/field.field.citation.su_article_journal.su_author.yml
  config/sync/field.field.citation.su_article_newspaper.su_author.yml
  config/sync/field.field.citation.su_book.su_author.yml
  config/sync/field.field.citation.su_other.su_author.yml
  config/sync/field.field.citation.su_thesis.su_author.yml
  tests/codeception/acceptance/Content/PublicationsCest.php
Labels: size/xs

#403 8.2.6 hotfix: added experimental label to basic page type field and view
  CHANGELOG.md
  config/sync/field.field.citation.su_article_journal.su_author.yml
  config/sync/field.field.citation.su_article_newspaper.su_author.yml
  config/sync/field.field.citation.su_book.su_author.yml
  config/sync/field.field.citation.su_other.su_author.yml
  config/sync/field.field.citation.su_thesis.su_author.yml
  config/sync/field.field.node.stanford_page.su_basic_page_type.yml
  config/sync/views.view.stanford_basic_pages.yml
  stanford_profile.info.yml
  tests/codeception/acceptance/Content/BasicPageCest.php
  tests/codeception/acceptance/Content/PublicationsCest.php
Labels: patch, size/xs

#406 8.2.7
  CHANGELOG.md
  config/sync/core.entity_view_display.node.stanford_news.stanford_card.yml
  config/sync/taxonomy.vocabulary.basic_page_types.yml
  stanford_profile.info.yml
Labels: patch, size/xs

#407 D8CORE-2729 enable the hero banner behavior
  config/sync/paragraphs.paragraphs_type.stanford_banner.yml
  config/sync/user.role.contributor.yml
  config/sync/user.role.site_editor.yml
  config/sync/user.role.site_manager.yml
  tests/codeception/functional/Paragraphs/BannerCest.php
Labels: size/xs

#408 D8CORE-3104 D8CORE-3455 D8CORE-3456 D8CORE-3981 Help text and form tweaks
  config/sync/core.entity_form_display.node.stanford_event.default.yml
  config/sync/core.entity_form_display.paragraph.stanford_schedule.default.yml
  config/sync/field.field.node.stanford_event.su_event_alt_loc.yml
  config/sync/field.field.node.stanford_news.su_news_topics.yml
  config/sync/field.field.paragraph.stanford_entity.su_entity_item.yml
  config/sync/field.field.paragraph.stanford_lists.su_list_view.yml
Labels: size/xs
