Repository SU-SWS/stanford_profile, pull requests merged in 2021-03, with the labels that each got.

#362 D8CORE-3050 Added path redirect import module
  composer.json
  config/sync/core.extension.yml
  tests/codeception/acceptance/Content/PublicationsCest.php
  tests/codeception/functional/Contrib/RedirectImportCest.php
Labels: size/xs

#358 D8CORE-3463 Adjust the list and cards displays
  config/sync/core.entity_view_display.node.stanford_event.stanford_card.yml
  config/sync/views.view.stanford_events.yml
Labels: size/m

#370 D8CORE-3476 Create a new view display mode specific for viewfields
  config/sync/field.field.paragraph.stanford_lists.su_list_view.yml
  config/sync/views.view.stanford_events.yml
  config/sync/views.view.stanford_news.yml
  config/sync/views.view.stanford_person.yml
  config/sync/views.view.stanford_publications.yml
Labels: size/xs

#366 D8CORE-3520 All Publications list page
  composer.json
  config/sync/block.block.stanford_basic_pagetitle.yml
  config/sync/core.entity_view_display.citation.su_thesis.default.yml
  config/sync/core.entity_view_display.taxonomy_term.stanford_publication_topics.default.yml
  config/sync/field.field.citation.su_thesis.su_publisher.yml
  config/sync/field.field.citation.su_thesis.su_year.yml
  config/sync/system.menu.stanford-publication-topics.yml
  config/sync/taxonomy_menu.taxonomy_menu.publication_topics.yml
  config/sync/views.view.publication_terms.yml
  config/sync/views.view.stanford_publications.yml
  content/node/ce9cb7ca-6c59-4eea-9934-0a33057a7ff2.yml
  content/paragraph/9939d5e0-a261-4f99-b08a-9ba5b43908c1.yml
  content/paragraph_row/e9158340-cb5c-494e-9c66-a959208fe4a8.yml
  tests/codeception/acceptance/Content/PublicationsCest.php
Labels: size/m

#373 Updated contrib dependencies
  composer.json
  config/sync/admin_toolbar_tools.settings.yml
Labels: size/xs

#376 D8CORE-3576: fixing spacing after the results for on the filtered page
  config/sync/views.view.publication_terms.yml
Labels: size/xs

#377 Revert a previous pull request
  config/sync/views.view.publication_terms.yml
Labels: size/xs

#374 Add a checkbox to the config pages for the drop down menu setting.
  config/sync/config_pages.type.stanford_basic_site_settings.yml
  config/sync/core.entity_form_display.config_pages.stanford_basic_site_settings.default.yml
  config/sync/core.entity_view_display.config_pages.stanford_basic_site_settings.default.yml
  config/sync/field.field.config_pages.stanford_basic_site_settings.su_site_dropdowns.yml
  config/sync/field.storage.config_pages.su_site_dropdowns.yml
  tests/codeception/functional/Navigation/NavigationDropDownsCest.php
Labels: size/xs

#375 D8CORE-3565: fixing up merge conflicts. Removes the more publication …
  config/sync/views.view.stanford_publications.yml
Labels: size/xs

#378 D8CORE-3352-reroll: config changes for past events
  config/sync/page_manager.page.stanford_events_past.yml
  config/sync/page_manager.page_variant.stanford_events_past-layout_builder-0.yml
  config/sync/views.view.stanford_events.yml
Labels: size/l

#381 Add "include child orgs" checkbox for cap org importer
  config/sync/core.entity_form_display.config_pages.stanford_person_importer.default.yml
  config/sync/core.entity_view_display.config_pages.stanford_person_importer.default.yml
  config/sync/field.field.config_pages.stanford_person_importer.su_person_child_orgs.yml
  config/sync/field.storage.config_pages.su_person_child_orgs.yml
Labels: size/xs

#384 8.2.2
  CHANGELOG.md
  config/sync/core.entity_view_display.taxonomy_term.stanford_publication_topics.default.yml
  config/sync/field.field.paragraph_row.su_pub_rows.su_pubs_components.yml
  config/sync/views.view.publication_terms.yml
  config/sync/views.view.stanford_publications.yml
  stanford_profile.info.yml
Labels: patch, size/xs

#385 D8CORE-3948: adding the see all publications button to the view that …
  CHANGELOG.md
  config/sync/views.view.stanford_publications.yml
  stanford_profile.info.yml
Labels: patch, size/xs

#379 D8CORE-3126 Intranet Configs
  config/sync/config_ignore.settings.yml
  config/sync/config_pages.type.stanford_saml.yml
  config/sync/core.entity_form_display.config_pages.stanford_saml.default.yml
  config/sync/core.entity_form_display.node.stanford_event.default.yml
  config/sync/core.entity_form_display.node.stanford_event_series.default.yml
  config/sync/core.entity_form_display.node.stanford_news.default.yml
  config/sync/core.entity_form_display.node.stanford_page.default.yml
  config/sync/core.entity_form_display.node.stanford_person.default.yml
  config/sync/core.entity_form_display.node.stanford_publication.default.yml
  config/sync/core.entity_view_display.config_pages.stanford_saml.default.yml
  config/sync/core.entity_view_display.node.stanford_event.default.yml
  config/sync/core.entity_view_display.node.stanford_event.stanford_card.yml
  config/sync/core.entity_view_display.node.stanford_event.teaser.yml
  config/sync/core.entity_view_display.node.stanford_event_series.default.yml
  config/sync/core.entity_view_display.node.stanford_event_series.stanford_card.yml
  config/sync/core.entity_view_display.node.stanford_event_series.teaser.yml
  config/sync/core.entity_view_display.node.stanford_news.default.yml
  config/sync/core.entity_view_display.node.stanford_news.stanford_card.yml
  config/sync/core.entity_view_display.node.stanford_page.default.yml
  config/sync/core.entity_view_display.node.stanford_page.stanford_card.yml
  config/sync/core.entity_view_display.node.stanford_person.default.yml
  config/sync/core.entity_view_display.node.stanford_person.stanford_card.yml
  config/sync/core.entity_view_display.node.stanford_person.teaser.yml
  config/sync/core.entity_view_display.node.stanford_publication.default.yml
  config/sync/core.entity_view_display.node.stanford_publication.teaser.yml
  config/sync/core.extension.yml
  config/sync/field.field.config_pages.stanford_saml.su_simplesaml_allowed.yml
  config/sync/field.field.config_pages.stanford_saml.su_simplesaml_users.yml
  config/sync/field.field.node.stanford_event.stanford_intranet__access.yml
  config/sync/field.field.node.stanford_event_series.stanford_intranet__access.yml
  config/sync/field.field.node.stanford_news.stanford_intranet__access.yml
  config/sync/field.field.node.stanford_page.stanford_intranet__access.yml
  config/sync/field.field.node.stanford_person.stanford_intranet__access.yml
  config/sync/field.field.node.stanford_publication.stanford_intranet__access.yml
  config/sync/field.storage.config_pages.su_simplesaml_allowed.yml
  config/sync/field.storage.config_pages.su_simplesaml_users.yml
  config/sync/field.storage.node.stanford_intranet__access.yml
  config/sync/user.role.site_manager.yml
  tests/codeception/acceptance/Users/IntranetCest.php
Labels: patch, size/m

#386 D8CORE-3947: adding classes to the filtered by for publications
  config/sync/views.view.publication_terms.yml
Labels: patch, size/xs

#387 D8CORE-3536 Display publications as a teaser in the paragraph
  composer.json
  config/sync/core.entity_view_display.node.stanford_publication.default.yml
  config/sync/core.entity_view_display.node.stanford_publication.stanford_card.yml
  config/sync/field.field.paragraph.stanford_entity.su_entity_item.yml
  tests/codeception/functional/Paragraphs/EntityReferenceCest.php
Labels: size/s

#389 D8CORE-3458 Dont display unpublished profiles in the lists
  config/sync/views.view.stanford_person_list_terms_first.yml
  tests/codeception/acceptance/Content/PersonCest.php
Labels: size/xs

#390 D8CORE-3538 Add "Other" citation type
  config/sync/core.entity_form_display.citation.su_other.default.yml
  config/sync/core.entity_view_display.citation.su_other.default.yml
  config/sync/field.field.citation.su_other.su_author.yml
  config/sync/field.field.citation.su_other.su_day.yml
  config/sync/field.field.citation.su_other.su_month.yml
  config/sync/field.field.citation.su_other.su_publisher.yml
  config/sync/field.field.citation.su_other.su_subtitle.yml
  config/sync/field.field.citation.su_other.su_url.yml
  config/sync/field.field.citation.su_other.su_year.yml
  config/sync/field.field.node.stanford_publication.su_publication_citation.yml
  config/sync/stanford_publication.citation_type.su_other.yml
  config/sync/views.view.stanford_publications.yml
  tests/codeception/acceptance/Content/PublicationsCest.php
Labels: size/m

#392 D8CORE-2853 test for unpublishing the home page
  tests/codeception/acceptance/HomePageCest.php
Labels: size/xs
