Repository SU-SWS/stanford_profile, pull requests merged in 2021-05, with the labels that each got.

#409 D8CORE-3970: removed the extra h2
  config/sync/core.entity_view_display.node.stanford_event_series.stanford_card.yml
Labels: size/xs

#411 D8CORE-3951: fixing the pagination to the infinite scroll and a Load More button
  config/sync/views.view.stanford_publications.yml
Labels: size/xs

#405 D8CORE-4093: removing the margin top from the button on lists
  config/sync/core.entity_view_display.paragraph.stanford_lists.default.yml
Labels: size/xs

#412 D8CORE-3523: Added User Search form
  config/sync/views.view.user_search.yml
Labels: size/m

#410 D8CORE-4145: adding the margin bottom to the intro for events.
  config/sync/core.entity_view_display.block_content.stanford_component_block.default.yml
Labels: size/xs

#414 D8CORE-2028 Change "People" to "Users" in the admin toolbar
  config/sync/core.extension.yml
  config/sync/views.view.user_admin_people.yml
  tests/codeception/acceptance/AuthenticatedPermissionsCest.php
  tests/codeception/acceptance/Users/DefaultUsersCest.php
  tests/codeception/acceptance/Users/RolesCest.php
Labels: size/xs

#417 D8CORE-4215: Undoing the change to the button margin
  config/sync/core.entity_view_display.paragraph.stanford_lists.default.yml
Labels: patch, size/xs

#415 D8CORE-4104 Adjust colorbox settings
  config/sync/colorbox.settings.yml
Labels: size/xs

#413 "8.x-2.x 8.2.8
  CHANGELOG.md
  config/sync/core.entity_form_display.node.stanford_event.default.yml
  config/sync/core.entity_form_display.paragraph.stanford_schedule.default.yml
  config/sync/core.entity_view_display.block_content.stanford_component_block.default.yml
  config/sync/core.entity_view_display.node.stanford_event_series.stanford_card.yml
  config/sync/core.entity_view_display.paragraph.stanford_lists.default.yml
  config/sync/field.field.citation.su_article_journal.su_author.yml
  config/sync/field.field.citation.su_article_newspaper.su_author.yml
  config/sync/field.field.citation.su_book.su_author.yml
  config/sync/field.field.citation.su_other.su_author.yml
  config/sync/field.field.citation.su_thesis.su_author.yml
  config/sync/field.field.node.stanford_event.su_event_alt_loc.yml
  config/sync/field.field.node.stanford_news.su_news_topics.yml
  config/sync/field.field.paragraph.stanford_entity.su_entity_item.yml
  config/sync/field.field.paragraph.stanford_lists.su_list_view.yml
  config/sync/paragraphs.paragraphs_type.stanford_banner.yml
  config/sync/stanford_ssp.settings.yml
  config/sync/ultimate_cron.job.stanford_fields_cron.yml
  config/sync/user.role.contributor.yml
  config/sync/user.role.site_editor.yml
  config/sync/user.role.site_manager.yml
  config/sync/views.view.stanford_publications.yml
  config/sync/views.view.user_admin_people.yml
  stanford_profile.info.yml
  tests/codeception/functional/Paragraphs/BannerCest.php
Labels: patch, size/l

#422 D8CORE-2898 Removed the headline field in favor of title field
  config/sync/auto_entitylabel.settings.node.stanford_news.yml
  config/sync/core.base_field_override.node.stanford_news.title.yml
  config/sync/core.entity_form_display.node.stanford_news.default.yml
  config/sync/core.entity_view_display.node.stanford_news.default.yml
  config/sync/core.entity_view_display.node.stanford_news.stanford_card.yml
  config/sync/field.storage.node.su_news_headline.yml
  config/sync/views.view.stanford_news.yml
  tests/codeception/acceptance/Content/NewsCest.php
  tests/codeception/acceptance/Paragraphs/ListsCest.php
Labels: size/m

#420 D8CORE-3158 Enable more paragraph components on news and people
  config/sync/field.field.node.stanford_news.su_news_components.yml
  config/sync/field.field.node.stanford_person.su_person_components.yml
Labels: size/xs

#416 D8CORE-2520 reset configs for events refactored patterns
  config/sync/core.entity_view_display.node.stanford_event.stanford_card.yml
  config/sync/core.entity_view_display.node.stanford_event.teaser.yml
  config/sync/core.entity_view_display.paragraph.stanford_person_cta.default.yml
  config/sync/core.entity_view_display.paragraph.stanford_schedule.default.yml
  config/sync/views.view.stanford_event_series.yml
  config/sync/views.view.stanford_events.yml
  config/sync/views.view.stanford_events_past.yml
Labels: patch, size/s

#424 D8CORE-4339 Allow restriction based on the persons affiliation to the university
  config/sync/config_pages.type.stanford_saml.yml
  config/sync/core.entity_form_display.config_pages.stanford_saml.default.yml
  config/sync/core.entity_view_display.config_pages.stanford_saml.default.yml
  config/sync/field.field.config_pages.stanford_saml.su_simplesaml_affil.yml
  config/sync/field.storage.config_pages.su_simplesaml_affil.yml
  config/sync/stanford_ssp.settings.yml
Labels: size/xs
