Repository SU-SWS/stanford_profile, pull requests merged in 2021-02, with the labels that each got.

#353 D8CORE-3445: tweaking the label names and hiding extra fields
  config/sync/core.entity_view_display.citation.su_article_journal.default.yml
  config/sync/core.entity_view_display.citation.su_article_newspaper.default.yml
  config/sync/core.entity_view_display.citation.su_book.default.yml
  config/sync/core.entity_view_display.citation.su_thesis.default.yml
  config/sync/field.field.citation.su_article_journal.su_publisher.yml
  config/sync/field.field.citation.su_article_newspaper.su_publisher.yml
  config/sync/field.field.citation.su_thesis.su_publisher.yml
Labels: size/s

#352 Several configuration tweaks.
  config/sync/colorbox.settings.yml
  config/sync/core.entity_form_display.citation.su_article_journal.default.yml
  config/sync/core.entity_form_display.citation.su_article_newspaper.default.yml
  config/sync/core.entity_form_display.citation.su_book.default.yml
  config/sync/core.entity_form_display.citation.su_thesis.default.yml
  config/sync/core.entity_form_display.media.stanford_gallery_images.default.yml
  config/sync/core.entity_form_display.media.stanford_gallery_images.media_library.yml
  config/sync/core.entity_form_display.node.stanford_publication.default.yml
  config/sync/core.entity_form_display.paragraph.stanford_gallery.default.yml
  config/sync/core.entity_view_display.citation.su_article_journal.default.yml
  config/sync/core.entity_view_display.citation.su_article_newspaper.default.yml
  config/sync/core.entity_view_display.citation.su_book.default.yml
  config/sync/core.entity_view_display.citation.su_thesis.default.yml
  config/sync/core.entity_view_display.media.stanford_gallery_images.default.yml
  config/sync/core.entity_view_display.media.stanford_gallery_images.media_library.yml
  config/sync/core.entity_view_display.paragraph.stanford_gallery.default.yml
  config/sync/field.field.citation.su_article_journal.su_doi.yml
  config/sync/field.field.citation.su_article_journal.su_publisher.yml
  config/sync/field.field.citation.su_article_journal.su_url.yml
  config/sync/field.field.citation.su_article_newspaper.su_publisher.yml
  config/sync/field.field.citation.su_article_newspaper.su_url.yml
  config/sync/field.field.citation.su_book.su_doi.yml
  config/sync/field.field.citation.su_book.su_url.yml
  config/sync/field.field.citation.su_thesis.su_doi.yml
  config/sync/field.field.citation.su_thesis.su_publisher.yml
  config/sync/field.field.citation.su_thesis.su_url.yml
  config/sync/field.field.media.stanford_gallery_images.su_gallery_caption.yml
  config/sync/field.field.media.stanford_gallery_images.su_gallery_image.yml
  config/sync/field.field.node.stanford_publication.su_publication_citation.yml
  config/sync/field.field.paragraph.stanford_gallery.su_gallery_button.yml
  config/sync/field.field.paragraph.stanford_gallery.su_gallery_description.yml
  config/sync/field.field.paragraph.stanford_gallery.su_gallery_headline.yml
  config/sync/field.field.paragraph_row.node_stanford_page_row.su_page_components.yml
  config/sync/field.field.paragraph_row.su_pub_rows.su_pubs_components.yml
  config/sync/field.storage.media.su_gallery_caption.yml
  config/sync/field.storage.paragraph.su_gallery_button.yml
  config/sync/field.storage.paragraph.su_gallery_description.yml
  config/sync/field.storage.paragraph.su_gallery_headline.yml
  config/sync/field.storage.paragraph_row.su_pubs_components.yml
  config/sync/paragraphs.paragraphs_type.stanford_gallery.yml
  config/sync/views.view.stanford_publications.yml
Labels: size/m

#354 D8CORE-2968 Change the events schedule view
  config/sync/core.entity_view_display.node.stanford_event.default.yml
  config/sync/views.view.stanford_events.yml
Labels: size/s

#356 D8CORE-3479: changing spacing on more cards
  config/sync/views.view.stanford_publications.yml
Labels: size/xs

#365 8.1.23
  CHANGELOG.md
  composer.json
  stanford_profile.info.yml
Labels: patch, size/xs

#359 Moved patches to shared package and use Stable 9 theme.
  composer.json
  config/sync/core.extension.yml
  stanford_profile.info.yml
Labels: patch, size/xs

#363 D8CORE-1531 Removed "Remove formatting" ckeditor button that does nothing
  config/sync/editor.editor.stanford_html.yml
Labels: size/xs

#364 D8CORE-3392 Changed the view blocks order and names
  config/sync/views.view.stanford_events.yml
  config/sync/views.view.stanford_news.yml
Labels: size/xs

#368 D8CORE-3482 D8CORE-3484 Adjustments to publication lists and fields
  config/sync/core.entity_view_display.node.stanford_publication.default.yml
  config/sync/field.field.node.stanford_publication.su_publication_citation.yml
  config/sync/field.field.node.stanford_publication.su_publication_topics.yml
  config/sync/views.view.stanford_publications.yml
Labels: size/m
