Repository SU-SWS/stanford_profile, pull requests merged in 2021-01, with the labels that each got.

#345 D8CORE-3142: adding a class to the intro block
  config/sync/core.entity_view_display.block_content.stanford_component_block.default.yml
  config/sync/field.field.block_content.stanford_component_block.su_component.yml
Labels: size/xs

#340 Exported configs after D9.1 database updates
  .circleci/config.yml
  composer.json
  config/sync/core.extension.yml
  config/sync/hal.settings.yml
  config/sync/rest.settings.yml
  config/sync/serialization.settings.yml
  src/Config/ConfigOverrides.php
  stanford_profile.info.yml
  tests/codeception/acceptance/Content/BasicPageCest.php
  tests/codeception/acceptance/Content/EventsCest.php
  tests/codeception/acceptance/Content/EventsSeriesCest.php
  tests/src/Unit/Config/ConfigOverridesTest.php
  tests/src/Unit/EventSubscriber/EventSubscriberTest.php
Labels: patch, size/s

#346 Updated patch for config_ignore
  composer.json
Labels: size/xs

#347 D8CORE-3263 Create gallery paragraph type with colorbox actions
  composer.json
  config/sync/colorbox.settings.yml
  config/sync/core.entity_form_display.media.stanford_gallery_images.default.yml
  config/sync/core.entity_form_display.media.stanford_gallery_images.media_library.yml
  config/sync/core.entity_form_display.node.stanford_page.default.yml
  config/sync/core.entity_form_display.paragraph.stanford_gallery.default.yml
  config/sync/core.entity_view_display.media.stanford_gallery_images.default.yml
  config/sync/core.entity_view_display.media.stanford_gallery_images.media_library.yml
  config/sync/core.entity_view_display.paragraph.stanford_gallery.default.yml
  config/sync/core.extension.yml
  config/sync/field.field.media.stanford_gallery_images.su_gallery_image.yml
  config/sync/field.field.paragraph.stanford_gallery.su_gallery_images.yml
  config/sync/field.storage.media.su_gallery_image.yml
  config/sync/field.storage.paragraph.su_gallery_images.yml
  config/sync/media.type.stanford_gallery_images.yml
  config/sync/migrate_plus.migration_group.default.yml
  config/sync/paragraphs.paragraphs_type.stanford_gallery.yml
  tests/codeception/functional/Paragraphs/GalleryCest.php
  tests/codeception/functional/Paragraphs/wordmark.jpg
Labels: size/s

#349 D8CORE-1123: added tests for dropdown menu
  tests/codeception/functional/Navigation/NavigationDropDownsCest.php
Labels: size/xs
