Repository SU-SWS/stanford_profile, pull requests merged in 2022-06, with the labels that each got.

#564 D8CORE-4489: fixing font sizes within tables
  modules/stanford_profile_styles/dist/css/base/admin/ckeditor.css
  modules/stanford_profile_styles/dist/css/base/admin/field_widgets.css
  modules/stanford_profile_styles/dist/css/base/admin/node_forms.css
  modules/stanford_profile_styles/dist/css/base/stanford_profile_styles.css
  modules/stanford_profile_styles/dist/css/base/views/search.css
  modules/stanford_profile_styles/dist/css/component/blocks/config_pages.super-footer.css
  modules/stanford_profile_styles/dist/css/component/node/stanford_page.css
  modules/stanford_profile_styles/dist/css/component/node/stanford_page.layout.full-width.css
  modules/stanford_profile_styles/dist/css/component/paragraph/gallery.css
  modules/stanford_profile_styles/dist/css/component/paragraph/react_paragraphs.css
  modules/stanford_profile_styles/dist/css/component/paragraph/spacer.css
  modules/stanford_profile_styles/dist/css/component/paragraph/wysiwyg.css
  modules/stanford_profile_styles/dist/css/layout/layout.css
  modules/stanford_profile_styles/lib/scss/component/paragraph/wysiwyg/_paragraph.scss
Labels: size/xs

#570 D8CORE-2274: Updated event sponsor field
  composer.json
  config/sync/core.entity_form_display.node.stanford_event.default.yml
  config/sync/core.extension.yml
  config/sync/field.field.node.stanford_event.su_event_sponsor.yml
  config/sync/field.storage.node.su_event_sponsor.yml
  modules/stanford_events/stanford_events.install
Labels: size/xs

#568 Move CircleCi to GH Actions
  .circleci/config.yml
  .github/workflows/tag_commits_to_main.yml
  .github/workflows/tests.yml
  tests/codeception/functional/Paragraphs/WYSIWYGCest.php
Labels: size/s

#566 Fix error when the access token expires
  config/sync/config_pages.type.stanford_events_importer.yml
  config/sync/config_pages.type.stanford_person_importer.yml
  config/sync/core.entity_form_display.config_pages.stanford_person_importer.default.yml
  config/sync/core.entity_view_display.config_pages.stanford_person_importer.default.yml
  config/sync/field.field.config_pages.stanford_person_importer.su_person_orphan.yml
  config/sync/field.storage.config_pages.su_person_orphan.yml
  config/sync/migrate_plus.migration.stanford_events_importer.yml
  config/sync/migrate_plus.migration.stanford_localist_importer.yml
  config/sync/migrate_plus.migration.su_stanford_person.yml
  modules/stanford_person/modules/stanford_person_importer/src/Cap.php
  modules/stanford_person/modules/stanford_person_importer/src/CapInterface.php
  modules/stanford_person/modules/stanford_person_importer/src/Config/ConfigOverrides.php
  modules/stanford_person/modules/stanford_person_importer/tests/src/Unit/CapTest.php
  modules/stanford_person/modules/stanford_person_importer/tests/src/Unit/Config/ConfigOverridesTest.php
Labels: size/s

#574 Improve event sponsor field update hook
  modules/stanford_events/stanford_events.install
Labels: size/xs

#573 D8CORE-4972 Provide aria-label input for links on paragraphs
  composer.json
  config/sync/core.entity_form_display.paragraph.stanford_banner.default.yml
  config/sync/core.entity_form_display.paragraph.stanford_card.default.yml
  config/sync/core.entity_form_display.paragraph.stanford_entity.default.yml
  config/sync/core.entity_form_display.paragraph.stanford_gallery.default.yml
  config/sync/core.entity_form_display.paragraph.stanford_lists.default.yml
  config/sync/core.entity_form_display.paragraph.stanford_media_caption.default.yml
  config/sync/core.extension.yml
  config/sync/field.field.paragraph.stanford_banner.su_banner_button.yml
  config/sync/field.field.paragraph.stanford_card.su_card_link.yml
  config/sync/field.field.paragraph.stanford_entity.su_entity_button.yml
  config/sync/field.field.paragraph.stanford_gallery.su_gallery_button.yml
  config/sync/field.field.paragraph.stanford_lists.su_list_button.yml
  config/sync/field.field.paragraph.stanford_media_caption.su_media_caption_link.yml
  config/sync/filter.format.stanford_html.yml
  config/sync/filter.format.stanford_minimal_html.yml
  modules/jumpstart_ui/jumpstart_ui.module
  tests/codeception/acceptance/Content/PublicationsCest.php
  tests/codeception/functional/BasicPage/BasicPageParagraphsCest.php
  tests/codeception/functional/Paragraphs/BannerCest.php
  tests/codeception/functional/Paragraphs/EntityReferenceCest.php
  tests/codeception/functional/Paragraphs/GalleryCest.php
  tests/codeception/functional/Paragraphs/WYSIWYGCest.php
Labels: size/s

#576 Drupal 9.4 support
  .circleci/config.yml
  composer.json
  config/sync/core.entity_view_display.config_pages.lockup_settings.default.yml
  config/sync/core.entity_view_display.media.embeddable.media_library.yml
  config/sync/core.entity_view_display.media.file.media_library.yml
  config/sync/core.entity_view_display.media.google_form.media_library.yml
  config/sync/core.entity_view_display.media.image.media_library.yml
  config/sync/core.entity_view_display.media.image.stanford_image_large.yml
  config/sync/core.entity_view_display.media.image.stanford_image_large_square.yml
  config/sync/core.entity_view_display.media.image.stanford_image_medium.yml
  config/sync/core.entity_view_display.media.image.stanford_image_medium_square.yml
  config/sync/core.entity_view_display.media.image.stanford_image_stanford_circle.yml
  config/sync/core.entity_view_display.media.image.stanford_image_thumb_square.yml
  config/sync/core.entity_view_display.media.image.thumbnail.yml
  config/sync/core.entity_view_display.media.stanford_gallery_images.media_library.yml
  config/sync/core.entity_view_display.media.video.media_library.yml
  config/sync/core.extension.yml
  config/sync/jsonapi.settings.yml
  config/sync/views.view.media.yml
  config/sync/views.view.media_library.yml
Labels: size/xs

#577 Adjusted functional tests
  tests/codeception/functional/BasicPage/BasicPageParagraphsCest.php
  tests/codeception/functional/Paragraphs/BannerCest.php
  tests/codeception/functional/Paragraphs/EntityReferenceCest.php
  tests/codeception/functional/Paragraphs/GalleryCest.php
  tests/codeception/functional/Paragraphs/WYSIWYGCest.php
Labels: size/s

#575 D8CORE-5862: Removed obsolete checkbox from theme settings
  config/sync/stanford_basic.settings.yml
  themes/stanford_basic/theme-settings.php
Labels: size/xs

#578 D8CORE-5948: removing the li from the ch line limit
  themes/stanford_basic/dist/css/components.css
  themes/stanford_basic/src/scss/components/wysiwyg/_line_length.scss
Labels: size/xs

#581 modify conflicting tests
  .github/workflows/tests.yml
  modules/jumpstart_ui/jumpstart_ui.module
  modules/stanford_profile_helper/stanford_profile_helper.module
  tests/codeception/acceptance/BasicPageComponentsCest.php
  tests/codeception/acceptance/Content/BasicPageCest.php
  tests/codeception/acceptance/Content/CoursesCest.php
  tests/codeception/acceptance/Content/CustomBlockCest.php
  tests/codeception/acceptance/Content/DefaultContentCest.php
  tests/codeception/acceptance/Content/EventsCest.php
  tests/codeception/acceptance/Content/EventsSeriesCest.php
  tests/codeception/acceptance/Content/NewsCest.php
  tests/codeception/acceptance/Content/PersonCest.php
  tests/codeception/acceptance/Content/PublicationsCest.php
  tests/codeception/acceptance/Contrib/NodeRevisionDeleteCest.php
  tests/codeception/acceptance/Contrib/ViewsBulkEditCest.php
  tests/codeception/acceptance/Contrib/XmlsitemapCest.php
  tests/codeception/acceptance/GlobalMessage/GlobalMessageCest.php
  tests/codeception/acceptance/HomePageCest.php
  tests/codeception/acceptance/LocalFooter/LocalFooterCest.php
  tests/codeception/acceptance/LocalFooter/LocalFooterLockupCest.php
  tests/codeception/acceptance/LockupSettings/LockupSettingsCest.php
  tests/codeception/acceptance/LockupSettings/logo.jpg
  tests/codeception/acceptance/Media/MediaCest.php
  tests/codeception/acceptance/Media/MediaFormsCest.php
  tests/codeception/acceptance/Media/MediaPermissionsCest.php
  tests/codeception/acceptance/Paragraphs/Issue2901390Cest.php
  tests/codeception/acceptance/Paragraphs/ListsCest.php
  tests/codeception/acceptance/Paragraphs/MediaWithCaptionCest.php
  tests/codeception/acceptance/Paragraphs/StanfordCardCest.php
  tests/codeception/acceptance/SubThemeCest.php
  tests/codeception/acceptance/SuperFooter/SuperFooterCest.php
  tests/codeception/acceptance/SystemSiteConfigCest.php
  tests/codeception/acceptance/TestFilesTrait.php
  tests/codeception/acceptance/Users/IntranetCest.php
  tests/codeception/acceptance/assets/logo.jpg
  tests/codeception/acceptance/assets/test.pdf
  tests/codeception/functional/BasicPage/BasicPageParagraphsCest.php
  tests/codeception/functional/Contrib/ExtLinkCest.php
  tests/codeception/functional/Contrib/RedirectImportCest.php
  tests/codeception/functional/Navigation/NavigationDropDownsCest.php
Labels: size/l

#579 D8CORE-5128 Enable embed code validators
  config/sync/field.field.media.embeddable.field_media_embeddable_code.yml
  config/sync/media.type.embeddable.yml
  modules/stanford_intranet/src/Config/ConfigOverrider.php
  tests/codeception/acceptance/Media/MediaCest.php
Labels: size/xs
