Repository SU-SWS/stanford_profile, pull requests merged in 2022-04, with the labels that each got.

#517 circle context
  .circleci/config.yml
Labels: size/xs

#515 D8CORE-5666 Enabled and configured responsive_tables_filter module
  composer.json
  config/sync/core.extension.yml
  config/sync/filter.format.stanford_html.yml
  config/sync/filter.format.stanford_minimal_html.yml
  config/sync/responsive_tables_filter.settings.yml
Labels: size/xs

#519 D8CORE-4118 Remove layout builder settings on other display modes
  config/sync/core.entity_view_display.node.stanford_event.search_indexing.yml
  config/sync/core.entity_view_display.node.stanford_event.stanford_card.yml
  config/sync/core.entity_view_display.node.stanford_event.teaser.yml
  config/sync/core.entity_view_display.node.stanford_event_series.search_indexing.yml
  config/sync/core.entity_view_display.node.stanford_event_series.stanford_card.yml
  config/sync/core.entity_view_display.node.stanford_event_series.teaser.yml
  config/sync/core.entity_view_display.node.stanford_news.search_indexing.yml
  config/sync/core.entity_view_display.node.stanford_news.stanford_card.yml
  config/sync/core.entity_view_display.node.stanford_page.search_indexing.yml
  config/sync/core.entity_view_display.node.stanford_page.stanford_card.yml
  config/sync/core.entity_view_display.node.stanford_person.search_indexing.yml
  config/sync/core.entity_view_display.node.stanford_person.stanford_card.yml
  config/sync/core.entity_view_display.node.stanford_person.teaser.yml
  config/sync/core.entity_view_display.node.stanford_publication.search_indexing.yml
  config/sync/core.entity_view_display.node.stanford_publication.stanford_card.yml
  config/sync/core.entity_view_display.node.stanford_publication.teaser.yml
  tests/codeception/acceptance/Paragraphs/ListsCest.php
Labels: size/s

#521 D8CORE-5629 Adjust profile link url for stanford only profiles
  config/sync/migrate_plus.migration.su_stanford_person.yml
Labels: size/xs

#520 D8CORE-5696 Only display location address once
  config/sync/ultimate_cron.job.domain_301_redirect_cron.yml
  config/sync/views.view.stanford_events.yml
  tests/codeception/acceptance/Content/EventsCest.php
Labels: size/xl

#522 localist terms
  config/sync/core.entity_form_display.node.stanford_event.default.yml
  config/sync/core.entity_form_display.taxonomy_term.stanford_event_groups.default.yml
  config/sync/core.entity_form_display.taxonomy_term.stanford_event_keywords.default.yml
  config/sync/core.entity_form_display.taxonomy_term.stanford_event_subject.default.yml
  config/sync/core.entity_view_display.node.stanford_event.default.yml
  config/sync/core.entity_view_display.node.stanford_event.search_indexing.yml
  config/sync/core.entity_view_display.node.stanford_event.stanford_card.yml
  config/sync/core.entity_view_display.node.stanford_event.teaser.yml
  config/sync/field.field.node.stanford_event.su_event_groups.yml
  config/sync/field.field.node.stanford_event.su_event_keywords.yml
  config/sync/field.field.node.stanford_event.su_event_subject.yml
  config/sync/field.storage.node.su_event_groups.yml
  config/sync/field.storage.node.su_event_keywords.yml
  config/sync/field.storage.node.su_event_subject.yml
  config/sync/migrate_plus.migration.stanford_events_importer.yml
  config/sync/migrate_plus.migration.stanford_localist_importer.yml
  config/sync/migrate_plus.migration.stanford_publications.yml
  config/sync/migrate_plus.migration.su_stanford_person.yml
  config/sync/taxonomy.vocabulary.stanford_event_groups.yml
  config/sync/taxonomy.vocabulary.stanford_event_keywords.yml
  config/sync/taxonomy.vocabulary.stanford_event_subject.yml
  config/sync/user.role.site_builder.yml
  config/sync/user.role.site_developer.yml
  config/sync/user.role.site_editor.yml
  config/sync/user.role.site_manager.yml
  config/sync/views.view.stanford_events.yml
  tests/codeception/acceptance/Paragraphs/ListsCest.php
Labels: size/l

#527 D8CORE-5768: changing to a list for the instructors
  config/sync/views.view.stanford_courses.yml
Labels: size/s

#528 D8CORE-5729 styling updates
  config/sync/views.view.taxonomy_term_pages.yml
Labels: size/xs

#526 D8CORE-5729 People term pages: display only child terms groupings
  config/sync/core.entity_view_display.taxonomy_term.stanford_person_types.default.yml
  config/sync/views.view.stanford_person.yml
  config/sync/views.view.taxonomy_term_pages.yml
  tests/codeception/acceptance/Content/PersonCest.php
Labels: size/m

#529 D8CORE-5627: added <object> and <param> to allowed tags in embeddables
  config/sync/core.entity_view_display.media.embeddable.default.yml
Labels: size/xs

#530 D8CORE-5778: adding the grid col 3 for three across
  config/sync/views.view.stanford_news.yml
  config/sync/views.view.stanford_publications.yml
Labels: size/xs

#533 D8CORE-5748: Adding a listy style to the taxonomy terms
  config/sync/core.entity_view_display.node.stanford_news.stanford_card.yml
  config/sync/core.entity_view_display.node.stanford_publication.stanford_card.yml
Labels: size/xs

#534 D8CORE-5772: Added custom block and edit link on `/courses` page
  config/sync/core.menu.static_menu_link_overrides.yml
  config/sync/page_manager.page_variant.courses_list_page-layout_builder-0.yml
  config/sync/views.view.su_block_edit_links.yml
  content/block_content/2f343c04-f892-49bb-8d28-2c3f4653b02a.yml
  stanford_profile.info.yml
  stanford_profile.post_update.php
  tests/codeception/acceptance/Content/CoursesCest.php
Labels: patch, size/s

#532 D8CORE 5750
  config/sync/core.entity_view_display.config_pages.stanford_local_footer.default.yml
  config/sync/core.entity_view_display.node.stanford_event.stanford_card.yml
  config/sync/core.entity_view_display.node.stanford_news.stanford_card.yml
  config/sync/core.entity_view_display.node.stanford_publication.stanford_card.yml
  config/sync/core.entity_view_display.taxonomy_term.stanford_event_types.default.yml
  config/sync/core.entity_view_display.taxonomy_term.stanford_news_topics.default.yml
  config/sync/core.entity_view_display.taxonomy_term.stanford_person_types.default.yml
  config/sync/core.entity_view_display.taxonomy_term.stanford_publication_topics.default.yml
  config/sync/field.field.node.stanford_event.su_event_type.yml
  config/sync/field.field.node.stanford_news.su_news_topics.yml
  config/sync/field.field.node.stanford_page.su_basic_page_type.yml
  config/sync/field.field.node.stanford_publication.su_publication_topics.yml
  config/sync/pathauto.pattern.course_nodes.yml
  config/sync/pathauto.pattern.event_nodes.yml
  config/sync/pathauto.pattern.event_series.yml
  config/sync/pathauto.pattern.news_nodes.yml
  config/sync/pathauto.pattern.person.yml
  config/sync/pathauto.pattern.stanford_publications.yml
  config/sync/taxonomy.vocabulary.basic_page_types.yml
  config/sync/taxonomy.vocabulary.event_audience.yml
  config/sync/taxonomy.vocabulary.stanford_event_types.yml
  config/sync/taxonomy.vocabulary.stanford_news_topics.yml
  config/sync/taxonomy.vocabulary.stanford_person_types.yml
  config/sync/taxonomy.vocabulary.stanford_publication_topics.yml
  config/sync/taxonomy.vocabulary.su_shared_tags.yml
  config/sync/user.role.site_builder.yml
  config/sync/user.role.site_developer.yml
  config/sync/user.role.site_manager.yml
  config/sync/views.view.stanford_basic_pages.yml
  tests/codeception/acceptance/Content/BasicPageCest.php
  tests/codeception/acceptance/Content/PersonCest.php
Labels: size/s
