Repository SU-SWS/stanford_profile, pull requests merged in 2022-03, with the labels that each got.

#496 D8CORE-4713 Added id attribute for several wysiwyg tags
  config/sync/filter.format.stanford_html.yml
Labels: size/xs

#498 D8CORE-5180 D8CORE-5227 Remove alt text on people images
  config/sync/core.entity_view_display.node.stanford_person.default.yml
  config/sync/views.view.stanford_person.yml
Labels: size/xs

#492 D8CORE-2893: test for the minimally branded subtheme
  composer.json
  tests/codeception/acceptance/SubThemeCest.php
Labels: size/xs

#503 conditional fields
  composer.json
  config/sync/core.entity_form_display.config_pages.lockup_settings.default.yml
  config/sync/core.entity_form_display.config_pages.stanford_local_footer.default.yml
  config/sync/core.entity_view_display.config_pages.lockup_settings.default.yml
  config/sync/core.entity_view_display.config_pages.stanford_local_footer.default.yml
  config/sync/core.extension.yml
  config/sync/field.field.config_pages.lockup_settings.su_intro.yml
  config/sync/field.field.config_pages.stanford_local_footer.su_local_foot_help.yml
  config/sync/field.storage.config_pages.su_intro.yml
  config/sync/field.storage.config_pages.su_local_foot_help.yml
  config/sync/filter.format.stanford_html.yml
  config/sync/ultimate_cron.job.core_event_dispatcher_cron.yml
Labels: size/m

#504 Process Localist html to fix <img> tag styles to attributes
  config/sync/core.extension.yml
  config/sync/filter.format.stanford_html.yml
  config/sync/migrate_plus.migration.stanford_localist_importer.yml
Labels: size/xs

#497 D8CORE-4526 Adjust full width layout for page title position
  config/sync/layout_library.layout.stanford_basic_page_full.yml
Labels: size/xs

#506 D8CORE-4704 Fix person list to show nested content
  config/sync/views.view.stanford_person_list_terms_first.yml
  tests/codeception/acceptance/Content/PersonCest.php
Labels: size/s

#505 D8CORE-3345 Updated path auto pattern for events, news, and people
  config/sync/pathauto.pattern.event_nodes.yml
  config/sync/pathauto.pattern.event_types.yml
  config/sync/pathauto.pattern.news_topics.yml
  config/sync/pathauto.pattern.person.yml
  config/sync/pathauto.pattern.stanford_publication_topics.yml
  config/sync/pathauto.pattern.stanford_publications.yml
  tests/codeception/acceptance/Content/PersonCest.php
Labels: size/xs

#508 Enable minimally branded theme for easier switching
  config/sync/block.block.minimally_branded_subtheme_branding.yml
  config/sync/block.block.minimally_branded_subtheme_config_pages.yml
  config/sync/block.block.minimally_branded_subtheme_config_pages_stanford_global_msg.yml
  config/sync/block.block.minimally_branded_subtheme_config_pages_stanford_super_footer.yml
  config/sync/block.block.minimally_branded_subtheme_content.yml
  config/sync/block.block.minimally_branded_subtheme_help.yml
  config/sync/block.block.minimally_branded_subtheme_local_tasks.yml
  config/sync/block.block.minimally_branded_subtheme_main_navigation.yml
  config/sync/block.block.minimally_branded_subtheme_messages.yml
  config/sync/block.block.minimally_branded_subtheme_pagetitle.yml
  config/sync/block.block.minimally_branded_subtheme_search.yml
  config/sync/block.block.minimally_branded_subtheme_search_form.yml
  config/sync/config_ignore.settings.yml
  config/sync/core.extension.yml
  tests/codeception/acceptance/SubThemeCest.php
Labels: size/s

#509 Configure layout builder restrictions consistently
  config/sync/core.entity_view_display.node.stanford_event.default.yml
  config/sync/core.entity_view_display.node.stanford_event_series.default.yml
  config/sync/core.entity_view_display.node.stanford_news.default.yml
  config/sync/core.entity_view_display.node.stanford_page.default.yml
  config/sync/core.entity_view_display.node.stanford_person.default.yml
  config/sync/core.entity_view_display.node.stanford_publication.default.yml
Labels: size/m

#477 D8CORE-5172: Updated references to localist and events-legacy urls
  config/sync/core.entity_form_display.config_pages.stanford_events_importer.default.yml
  config/sync/node.type.stanford_event.yml
  tests/codeception/acceptance/Content/EventsCest.php
  tests/codeception/acceptance/Media/MediaPermissionsCest.php
Labels: size/xs

#514 8.3.2
  CHANGELOG.md
  config/sync/core.entity_form_display.config_pages.stanford_events_importer.default.yml
  config/sync/field.field.config_pages.lockup_settings.su_lockup_options.yml
  config/sync/node.type.stanford_event.yml
  config/sync/views.view.content.yml
  stanford_profile.info.yml
  tests/codeception/acceptance/Content/EventsCest.php
  tests/codeception/acceptance/Media/MediaPermissionsCest.php
Labels: patch, size/xs

#516 Update label.yml
  .github/workflows/label.yml
Labels: size/xl
