Repository SU-SWS/stanford_profile, pull requests merged in 2022-05, with the labels that each got.

#536 updated dev dependencies
  composer.json
Labels: size/xs

#539 D8CORE-5833: Fix for courses view to respect item limit in card grid
  config/sync/views.view.stanford_courses.yml
Labels: size/xs

#541 8.4.1
  CHANGELOG.md
  composer.json
  config/sync/config_pages.type.stanford_basic_site_settings.yml
  config/sync/core.entity_form_display.config_pages.stanford_basic_site_settings.default.yml
  config/sync/core.entity_view_display.config_pages.stanford_basic_site_settings.default.yml
  config/sync/field.field.config_pages.stanford_basic_site_settings.su_site_403.yml
  config/sync/field.field.config_pages.stanford_basic_site_settings.su_site_404.yml
  config/sync/field.field.config_pages.stanford_basic_site_settings.su_site_home.yml
  config/sync/field.field.paragraph.stanford_media_caption.su_media_caption_caption.yml
  config/sync/field.storage.config_pages.su_site_403.yml
  config/sync/field.storage.config_pages.su_site_404.yml
  config/sync/field.storage.config_pages.su_site_home.yml
  config/sync/migrate_plus.migration.stanford_course_depts.yml
  config/sync/migrate_plus.migration.stanford_courses.yml
  config/sync/user.role.anonymous.yml
  config/sync/user.role.authenticated.yml
  config/sync/views.view.stanford_courses.yml
  config/sync/views.view.taxonomy_term_pages.yml
  stanford_profile.info.yml
  stanford_profile.services.yml
  tests/codeception/acceptance/Contrib/ViewsBulkEditCest.php
  tests/codeception/acceptance/LocalFooter/LocalFooterCest.php
  tests/codeception/acceptance/LocalFooter/LocalFooterLockupCest.php
  tests/codeception/acceptance/Media/MediaCest.php
  tests/codeception/acceptance/Paragraphs/ListsCest.php
  tests/codeception/acceptance/SystemSiteConfigCest.php
  tests/codeception/functional/Contrib/ExtLinkCest.php
  tests/codeception/functional/Paragraphs/EntityReferenceCest.php
Labels: patch, size/m

#544 8.4.1
  CHANGELOG.md
  config/sync/config_pages.type.stanford_basic_site_settings.yml
  config/sync/core.entity_form_display.config_pages.stanford_basic_site_settings.default.yml
  config/sync/core.entity_view_display.config_pages.stanford_basic_site_settings.default.yml
  config/sync/field.field.config_pages.stanford_basic_site_settings.su_site_403.yml
  config/sync/field.field.config_pages.stanford_basic_site_settings.su_site_404.yml
  config/sync/field.field.config_pages.stanford_basic_site_settings.su_site_home.yml
  config/sync/field.field.paragraph.stanford_media_caption.su_media_caption_caption.yml
  config/sync/field.storage.config_pages.su_site_403.yml
  config/sync/field.storage.config_pages.su_site_404.yml
  config/sync/field.storage.config_pages.su_site_home.yml
  config/sync/migrate_plus.migration.stanford_course_depts.yml
  config/sync/migrate_plus.migration.stanford_courses.yml
  config/sync/user.role.anonymous.yml
  config/sync/user.role.authenticated.yml
  config/sync/views.view.stanford_courses.yml
  config/sync/views.view.taxonomy_term_pages.yml
  stanford_profile.info.yml
  stanford_profile.services.yml
  tests/codeception/acceptance/Contrib/ViewsBulkEditCest.php
  tests/codeception/acceptance/LocalFooter/LocalFooterCest.php
  tests/codeception/acceptance/LocalFooter/LocalFooterLockupCest.php
  tests/codeception/acceptance/Media/MediaCest.php
  tests/codeception/acceptance/Paragraphs/ListsCest.php
  tests/codeception/acceptance/SystemSiteConfigCest.php
  tests/codeception/functional/Contrib/ExtLinkCest.php
  tests/codeception/functional/Paragraphs/EntityReferenceCest.php
Labels: patch, size/m

#545 8.4.2
  CHANGELOG.md
  composer.json
  config/sync/views.view.stanford_courses.yml
  stanford_profile.info.yml
Labels: patch, size/xs

#547 Updated submodules
  modules/jumpstart_ui/LICENSE.txt
  modules/jumpstart_ui/jumpstart_ui.info.yml
  modules/stanford_basic_page_types/dist/css/component/stanford-page.css
  modules/stanford_basic_page_types/lib/scss/component/stanford-page/index.scss
  modules/stanford_basic_page_types/stanford_basic_page_types.info.yml
  modules/stanford_courses/.circleci/README.md
  modules/stanford_courses/.circleci/config.yml
  modules/stanford_courses/.codeclimate.yml
  modules/stanford_courses/modules/stanford_courses_importer/stanford_courses_importer.info.yml
  modules/stanford_courses/stanford_courses.info.yml
  modules/stanford_events/LICENSE.txt
  modules/stanford_image_styles/.circleci/config.yml
  modules/stanford_intranet/drush.services.yml
  modules/stanford_intranet/lib/scss/base/intranet.scss
  modules/stanford_intranet/src/Commands/IntranetCommands.php
  modules/stanford_intranet/src/StanfordIntranetManager.php
  modules/stanford_intranet/src/StanfordIntranetManagerInterface.php
  modules/stanford_intranet/stanford_intranet.info.yml
  modules/stanford_intranet/stanford_intranet.install
  modules/stanford_intranet/stanford_intranet.services.yml
  modules/stanford_intranet/tests/src/Kernel/Commands/IntranetCommandsTest.php
  modules/stanford_intranet/tests/src/Kernel/IntranetKernelTestBase.php
  modules/stanford_intranet/tests/src/Kernel/StanfordIntranetManagerTest.php
  modules/stanford_news/stanford_news.info.yml
  modules/stanford_notifications/LICENSE.txt
  modules/stanford_notifications/stanford_notifications.info.yml
  modules/stanford_paragraph_card/stanford_paragraph_card.info.yml
  modules/stanford_person/LICENSE.txt
  modules/stanford_person/dist/css/stanford_person.views.css
  modules/stanford_person/lib/scss/stanford_person.views.scss
  modules/stanford_person/modules/stanford_person_importer/stanford_person_importer.info.yml
  modules/stanford_person/stanford_person.info.yml
  modules/stanford_profile_drush/stanford_profile_drush.info.yml
  modules/stanford_profile_helper/LICENSE.txt
  modules/stanford_profile_helper/stanford_profile_helper.info.yml
  modules/stanford_profile_helper/stanford_profile_helper.module
  modules/stanford_profile_helper/stanford_profile_helper.post_update.php
  modules/stanford_profile_helper/stanford_profile_helper.services.yml
  modules/stanford_profile_styles/dist/css/base/admin/ckeditor.css
  modules/stanford_profile_styles/dist/css/base/stanford_profile_styles.css
  modules/stanford_profile_styles/dist/css/component/node/stanford_page.css
  modules/stanford_profile_styles/dist/css/component/paragraph/wysiwyg.css
  modules/stanford_profile_styles/lib/scss/base/admin/ckeditor.scss
  modules/stanford_profile_styles/lib/scss/base/stanford_profile_styles.scss
  modules/stanford_profile_styles/lib/scss/component/node/stanford_page.scss
  modules/stanford_profile_styles/lib/scss/component/paragraph/react_paragraphs/index.scss
  modules/stanford_profile_styles/lib/scss/component/paragraph/spacer/index.scss
  modules/stanford_profile_styles/lib/scss/component/paragraph/wysiwyg/_paragraph.scss
  modules/stanford_profile_styles/lib/scss/component/paragraph/wysiwyg/_table.scss
  modules/stanford_profile_styles/lib/scss/component/paragraph/wysiwyg/index.scss
  modules/stanford_profile_styles/stanford_profile_styles.info.yml
  modules/stanford_profile_styles/stanford_profile_styles.module
  modules/stanford_publication/LICENSE.txt
  modules/stanford_publication/stanford_publication.info.yml
  modules/stanford_text_editor/LICENSE.txt
Labels: patch, size/l

#548 D8CORE-5824: Added a second provider for Stanford University Library oEmbeds
  config/sync/oembed_providers.provider.sul_embed_service.yml
  tests/codeception/acceptance/Media/MediaCest.php
Labels: patch, size/xs

#551 D8CORE-2215: Let editors sort content by author
  config/sync/views.view.content.yml
Labels: size/xs

#553 8.4.4
  CHANGELOG.md
  composer.json
  config/sync/migrate_plus.migration.stanford_course_depts.yml
  config/sync/migrate_plus.migration.stanford_courses.yml
  stanford_profile.info.yml
Labels: patch, size/xs

#550 D8CORE-1835: Added abbr buttons to ckeditor
  config/sync/filter.format.stanford_html.yml
Labels: patch, size/xs

#555 D8CORE-5773: Added edit buttons on courses list page
  config/sync/migrate_plus.migration.stanford_courses.yml
  config/sync/views.view.stanford_courses.yml
  modules/stanford_courses/dist/css/course-list-item.css
  modules/stanford_courses/dist/js/stanford_courses.script.js.map
  modules/stanford_courses/lib/scss/course-list-item.scss
Labels: size/s

#560 Locked citeprocphp to version 2.4.1, pre ext-intl requirement.
  composer.json
Labels: size/xs

#561 D8CORE-4867 Publication lists on people pages
  config/sync/core.entity_form_display.node.stanford_publication.default.yml
  config/sync/core.entity_view_display.node.stanford_person.default.yml
  config/sync/core.entity_view_display.node.stanford_publication.default.yml
  config/sync/core.entity_view_display.node.stanford_publication.search_indexing.yml
  config/sync/core.entity_view_display.node.stanford_publication.stanford_card.yml
  config/sync/core.entity_view_display.node.stanford_publication.teaser.yml
  config/sync/field.field.node.stanford_publication.su_publication_author_ref.yml
  config/sync/field.storage.node.su_publication_author_ref.yml
  config/sync/views.view.stanford_publications.yml
  tests/codeception/acceptance/Content/PublicationsCest.php
Labels: size/s

#562 D8CORE-5859: changes to the font sizes in courses
  modules/stanford_courses/dist/css/course-list-item.css
  modules/stanford_courses/dist/css/course-vertical-teaser.css
  modules/stanford_courses/lib/scss/course-list-item.scss
  modules/stanford_courses/lib/scss/course-vertical-teaser.scss
Labels: size/xs

#559 D8CORE-5864: fixing the news alignment.
  modules/stanford_news/dist/css/news-list-item.css
  modules/stanford_news/lib/scss/components/news-list-item/_list-item.scss
Labels: size/xs

#563 D8CORE-4858 Allow hiding paragraph and custom empty results message
  config/sync/config_pages.type.stanford_events_importer.yml
  config/sync/core.entity_form_display.config_pages.stanford_events_importer.default.yml
  config/sync/core.entity_view_display.config_pages.stanford_events_importer.default.yml
  config/sync/field.field.config_pages.stanford_events_importer.su_event_empty.yml
  config/sync/field.storage.config_pages.su_event_empty.yml
  config/sync/paragraphs.paragraphs_type.stanford_lists.yml
  config/sync/views.view.stanford_events.yml
  content/taxonomy_term/6a2ade62-d0bf-4f21-be92-fb5ad9a0bde0.yml
  content/taxonomy_term/6eaf9909-9f26-4e01-9121-34ecb577f0e0.yml
  content/taxonomy_term/80a4d81e-8eff-4138-8529-5bff4f7952c1.yml
  content/taxonomy_term/913f780a-62d6-4371-b8c4-ad39210bf80c.yml
  content/taxonomy_term/bb117bce-7413-4214-9e89-a831d5e8f69c.yml
  content/taxonomy_term/e6f319ee-8d87-4c59-8e18-e6b166b6d2cd.yml
  content/taxonomy_term/ec1ed532-edc7-464f-ba09-26958a42d8d0.yml
  content/taxonomy_term/f9979993-225b-4bdb-906f-daa2626332c5.yml
  modules/jumpstart_ui/src/Plugin/paragraphs/Behavior/HeroPatternBehavior.php
  modules/jumpstart_ui/src/Plugin/paragraphs/Behavior/ListParagraphBehavior.php
  modules/jumpstart_ui/tests/src/Unit/Plugin/paragraphs/Behavior/ListParagraphBehaviorTest.php
  modules/stanford_events/modules/stanford_events_importer/stanford_events_importer.module
  tests/codeception/acceptance/Content/EventsCest.php
  tests/codeception/acceptance/Paragraphs/ListsCest.php
Labels: size/m
