Repository SU-SWS/stanford_profile, pull requests merged in 2022-07, with the labels that each got.

#583 D8CORE-6003 Save terms in the order they were chosen
  tests/codeception/acceptance/Content/NewsCest.php
  tests/codeception/functional/Content/BasicPageParagraphsCest.php
  tests/codeception/functional/Content/StanfordNewsCest.php
Labels: size/s

#569 D8CORE-4183: fix up to alignment.
  modules/stanford_profile_styles/dist/css/base/admin/ckeditor.css
  modules/stanford_profile_styles/dist/css/base/admin/field_widgets.css
  modules/stanford_profile_styles/dist/css/base/admin/node_forms.css
  modules/stanford_profile_styles/dist/css/base/stanford_profile_styles.css
  modules/stanford_profile_styles/dist/css/base/views/search.css
  modules/stanford_profile_styles/dist/css/component/blocks/config_pages.super-footer.css
  modules/stanford_profile_styles/dist/css/component/node/stanford_page.css
  modules/stanford_profile_styles/dist/css/component/node/stanford_page.layout.full-width.css
  modules/stanford_profile_styles/dist/css/component/paragraph/gallery.css
  modules/stanford_profile_styles/dist/css/component/paragraph/react_paragraphs.css
  modules/stanford_profile_styles/dist/css/component/paragraph/spacer.css
  modules/stanford_profile_styles/dist/css/component/paragraph/wysiwyg.css
  modules/stanford_profile_styles/dist/css/layout/layout.css
  modules/stanford_profile_styles/lib/scss/component/node/stanford_page.scss
Labels: size/xl

#584 D8CORE-6000: Added additional html elements to embeddables allow list
  config/sync/core.entity_view_display.media.embeddable.default.yml
  tests/codeception/acceptance/Media/MediaCest.php
Labels: size/xs

#585 8.4.6
  CHANGELOG.md
  stanford_profile.info.yml
  tests/codeception/acceptance/Content/DefaultContentCest.php
  tests/codeception/acceptance/Content/NewsCest.php
  tests/codeception/acceptance/Content/PersonCest.php
  tests/codeception/acceptance/LocalFooter/LocalFooterCest.php
  tests/codeception/acceptance/Media/MediaCest.php
  tests/codeception/acceptance/SystemSiteConfigCest.php
Labels: patch, size/xs

#586 D8CORE-5684: moving change to the n3.0.0 release
  modules/stanford_events/pdb_components/mini-calendar/build/static/css/main.css
  modules/stanford_events/pdb_components/mini-calendar/src/styles.scss
  tests/codeception/acceptance/Content/EventsCest.php
  tests/codeception/acceptance/LocalFooter/LocalFooterCest.php
  tests/codeception/acceptance/SystemSiteConfigCest.php
Labels: size/xs

#587 8.4.7
  CHANGELOG.md
  stanford_profile.info.yml
Labels: patch, size/xs

#588 8.5.0
  CHANGELOG.md
  composer.json
  config/sync/field.storage.config_pages.su_person_cap_password.yml
  config/sync/field.storage.config_pages.su_person_cap_username.yml
  config/sync/field_encrypt.settings.yml
  config/sync/ultimate_cron.job.field_encrypt_cron.yml
  stanford_profile.info.yml
Labels: size/xs, minor

#591 D8CORE-5975 Allow resetting taxonomy term order to alphabetical with the button
  modules/stanford_profile_helper/stanford_profile_helper.module
Labels: size/xs

#595 Update StanfordTextEditorTest
  modules/stanford_text_editor/config/install/editor.editor.stanford_minimal_html.yml
  modules/stanford_text_editor/tests/src/Kernel/StanfordTextEditorTest.php
Labels: size/xs
