Repository SU-SWS/stanford_profile, pull requests merged in 2022-09, with the labels that each got.

#612 D8CORE-6245: fix to the transparent localist event link
  modules/stanford_profile_styles/dist/css/base/admin/ckeditor.css
  modules/stanford_profile_styles/dist/css/base/admin/field_widgets.css
  modules/stanford_profile_styles/dist/css/base/admin/node_forms.css
  modules/stanford_profile_styles/dist/css/base/stanford_profile_styles.css
  modules/stanford_profile_styles/dist/css/base/views/search.css
  modules/stanford_profile_styles/dist/css/component/blocks/config_pages.super-footer.css
  modules/stanford_profile_styles/dist/css/component/node/stanford_page.css
  modules/stanford_profile_styles/dist/css/component/node/stanford_page.layout.full-width.css
  modules/stanford_profile_styles/dist/css/component/paragraph/gallery.css
  modules/stanford_profile_styles/dist/css/component/paragraph/react_paragraphs.css
  modules/stanford_profile_styles/dist/css/component/paragraph/spacer.css
  modules/stanford_profile_styles/dist/css/component/paragraph/wysiwyg.css
  modules/stanford_profile_styles/dist/css/layout/layout.css
  modules/stanford_profile_styles/lib/scss/component/paragraph/wysiwyg/_headings.scss
Labels: size/xl

#609 D8CORE-5825 Add taxonomy field to media types for categorization
  composer.json
  config/sync/core.entity_form_display.media.file.default.yml
  config/sync/core.entity_form_display.media.file.media_library.yml
  config/sync/core.entity_form_display.media.image.default.yml
  config/sync/core.entity_form_display.media.image.media_library.yml
  config/sync/core.entity_form_display.media.stanford_gallery_images.default.yml
  config/sync/core.entity_form_display.media.stanford_gallery_images.media_library.yml
  config/sync/core.entity_form_display.media.video.default.yml
  config/sync/core.entity_form_display.media.video.media_library.yml
  config/sync/core.entity_view_display.media.file.default.yml
  config/sync/core.entity_view_display.media.file.media_library.yml
  config/sync/core.entity_view_display.media.image.default.yml
  config/sync/core.entity_view_display.media.image.media_library.yml
  config/sync/core.entity_view_display.media.image.stanford_image_large.yml
  config/sync/core.entity_view_display.media.image.stanford_image_large_square.yml
  config/sync/core.entity_view_display.media.image.stanford_image_medium.yml
  config/sync/core.entity_view_display.media.image.stanford_image_medium_square.yml
  config/sync/core.entity_view_display.media.image.stanford_image_stanford_circle.yml
  config/sync/core.entity_view_display.media.image.stanford_image_thumb_square.yml
  config/sync/core.entity_view_display.media.image.thumbnail.yml
  config/sync/core.entity_view_display.media.stanford_gallery_images.default.yml
  config/sync/core.entity_view_display.media.stanford_gallery_images.media_library.yml
  config/sync/core.entity_view_display.media.video.default.yml
  config/sync/core.entity_view_display.media.video.full.yml
  config/sync/core.entity_view_display.media.video.media_library.yml
  config/sync/core.extension.yml
  config/sync/field.field.media.file.su_media_category.yml
  config/sync/field.field.media.image.su_media_category.yml
  config/sync/field.field.media.stanford_gallery_images.su_media_category.yml
  config/sync/field.field.media.video.su_media_category.yml
  config/sync/field.storage.media.su_media_category.yml
  config/sync/rabbit_hole.behavior_settings.taxonomy_vocabulary_media_tags.yml
  config/sync/taxonomy.vocabulary.media_tags.yml
  config/sync/taxonomy_entity_index.settings.yml
  config/sync/views.settings.yml
  config/sync/views.view.media.yml
  config/sync/views.view.media_library.yml
  modules/stanford_profile_helper/src/EventSubscriber/ViewsEventSubscriber.php
  modules/stanford_profile_helper/stanford_profile_helper.info.yml
  modules/stanford_profile_helper/stanford_profile_helper.module
  modules/stanford_profile_helper/stanford_profile_helper.services.yml
  modules/stanford_profile_helper/tests/src/Kernel/EventSubscriber/EntityEventSubscriberTest.php
  modules/stanford_profile_helper/tests/src/Kernel/EventSubscriber/ViewsEventSubscriberTest.php
  modules/stanford_profile_helper/tests/src/Kernel/SuProfileHelperKernelTestBase.php
  tests/codeception/acceptance/Media/MediaCest.php
  tests/codeception/functional/Paragraphs/WYSIWYGCest.php
Labels: patch, size/l

#611 D8CORE-6217 Allow configuring maximum main menu depth
  config/sync/config_pages.type.stanford_basic_site_settings.yml
  config/sync/core.entity_form_display.config_pages.stanford_basic_site_settings.default.yml
  config/sync/core.entity_view_display.config_pages.stanford_basic_site_settings.default.yml
  config/sync/field.field.config_pages.stanford_basic_site_settings.su_site_menu_levels.yml
  config/sync/field.storage.config_pages.su_site_menu_levels.yml
  modules/stanford_profile_helper/src/Config/ConfigOverrides.php
  modules/stanford_profile_helper/tests/src/Unit/Config/ConfigOverridesTest.php
  tests/codeception/acceptance/LockupSettings/LockupSettingsCest.php
Labels: size/m

#608 D8CORE-6058 Adjust, improve, and add metatags for content
  composer.json
  config/sync/core.entity_form_display.node.stanford_course.default.yml
  config/sync/core.entity_form_display.node.stanford_event.default.yml
  config/sync/core.entity_form_display.node.stanford_event_series.default.yml
  config/sync/core.entity_form_display.node.stanford_news.default.yml
  config/sync/core.entity_form_display.node.stanford_page.default.yml
  config/sync/core.entity_form_display.node.stanford_person.default.yml
  config/sync/core.entity_form_display.node.stanford_publication.default.yml
  config/sync/core.entity_view_display.node.stanford_course.default.yml
  config/sync/core.entity_view_display.node.stanford_course.stanford_card.yml
  config/sync/core.entity_view_display.node.stanford_course.teaser.yml
  config/sync/core.entity_view_display.node.stanford_event.default.yml
  config/sync/core.entity_view_display.node.stanford_event.search_indexing.yml
  config/sync/core.entity_view_display.node.stanford_event.stanford_card.yml
  config/sync/core.entity_view_display.node.stanford_event.teaser.yml
  config/sync/core.entity_view_display.node.stanford_event_series.default.yml
  config/sync/core.entity_view_display.node.stanford_event_series.search_indexing.yml
  config/sync/core.entity_view_display.node.stanford_event_series.stanford_card.yml
  config/sync/core.entity_view_display.node.stanford_event_series.teaser.yml
  config/sync/core.entity_view_display.node.stanford_news.default.yml
  config/sync/core.entity_view_display.node.stanford_news.search_indexing.yml
  config/sync/core.entity_view_display.node.stanford_news.stanford_card.yml
  config/sync/core.entity_view_display.node.stanford_page.default.yml
  config/sync/core.entity_view_display.node.stanford_page.search_indexing.yml
  config/sync/core.entity_view_display.node.stanford_page.stanford_card.yml
  config/sync/core.entity_view_display.node.stanford_person.default.yml
  config/sync/core.entity_view_display.node.stanford_person.search_indexing.yml
  config/sync/core.entity_view_display.node.stanford_person.stanford_card.yml
  config/sync/core.entity_view_display.node.stanford_person.teaser.yml
  config/sync/core.entity_view_display.node.stanford_publication.default.yml
  config/sync/core.entity_view_display.node.stanford_publication.search_indexing.yml
  config/sync/core.entity_view_display.node.stanford_publication.stanford_card.yml
  config/sync/core.entity_view_display.node.stanford_publication.teaser.yml
  config/sync/core.extension.yml
  config/sync/field.field.node.stanford_course.su_metatags.yml
  config/sync/field.field.node.stanford_event.su_metatags.yml
  config/sync/field.field.node.stanford_event_series.su_metatags.yml
  config/sync/field.field.node.stanford_news.su_metatags.yml
  config/sync/field.field.node.stanford_page.su_metatags.yml
  config/sync/field.field.node.stanford_page.su_page_description.yml
  config/sync/field.field.node.stanford_person.su_metatags.yml
  config/sync/field.field.node.stanford_publication.su_metatags.yml
  config/sync/field.storage.node.su_metatags.yml
  config/sync/filter.format.stanford_html.yml
  config/sync/metatag.metatag_defaults.front.yml
  config/sync/metatag.metatag_defaults.global.yml
  config/sync/metatag.metatag_defaults.node.yml
  config/sync/metatag.metatag_defaults.node__stanford_news.yml
  config/sync/metatag.metatag_defaults.node__stanford_person.yml
  config/sync/metatag.metatag_defaults.page_variant__people-layout_builder-0.yml
  config/sync/metatag.metatag_defaults.page_variant__stanford_news_list-layout_builder-0.yml
  config/sync/metatag.metatag_defaults.page_variant__stanford_news_list_terms-layout_builder-0.yml
  config/sync/metatag.metatag_defaults.page_variant__stanford_person_list-layout_builder-1.yml
  config/sync/metatag.settings.yml
  config/sync/user.role.anonymous.yml
  config/sync/user.role.authenticated.yml
  modules/stanford_basic_page_types/stanford_basic_page_types.module
  tests/codeception/acceptance/Content/BasicPageCest.php
  tests/codeception/acceptance/Content/NewsCest.php
  tests/codeception/acceptance/Content/PersonCest.php
Labels: size/m

#613 D8CORE-6235 Fix "Save and Import" on events importer form.
  composer.json
  config/sync/colorbox.settings.yml
  modules/stanford_courses/modules/stanford_courses_importer/stanford_courses_importer.module
  modules/stanford_events/modules/stanford_events_importer/stanford_events_importer.module
Labels: size/xs

#610 D8CORE-4363: having images appear on cards at xs breakpoint
  modules/jumpstart_ui/dist/css/card.css
  modules/jumpstart_ui/dist/js/jumpstart_ui.js.map
  modules/jumpstart_ui/lib/scss/components/card.component.scss
Labels: patch, size/xs

#614 D8CORE-6244: fixing float with a clear
  modules/jumpstart_ui/dist/css/media.css
  modules/jumpstart_ui/lib/scss/components/media.component.scss
Labels: size/xs

#618 Removed token_or patch
  composer.json
Labels: size/xs

#615 D8CORE-6242 D8CORE-4977 D8CORE-6055 Improve people lists and add pronoun field
  config/sync/colorbox.settings.yml
  config/sync/core.entity_form_display.node.stanford_person.default.yml
  config/sync/core.entity_view_display.node.stanford_person.default.yml
  config/sync/core.entity_view_display.node.stanford_person.search_indexing.yml
  config/sync/core.entity_view_display.node.stanford_person.stanford_card.yml
  config/sync/core.entity_view_display.node.stanford_person.teaser.yml
  config/sync/field.field.node.stanford_person.su_person_pronouns.yml
  config/sync/field.storage.node.su_person_pronouns.yml
  config/sync/google_analytics.settings.yml
  config/sync/views.view.stanford_person.yml
  config/sync/views.view.taxonomy_term_pages.yml
  modules/stanford_person/dist/css/stanford_person.node.css
  modules/stanford_person/dist/css/stanford_person.views.css
  modules/stanford_person/dist/js/stanford_person.script.js
  modules/stanford_person/dist/js/stanford_person.script.js.map
  modules/stanford_person/lib/scss/stanford_person.views.scss
  modules/stanford_person/stanford_person.module
  modules/stanford_person/yarn.lock
  modules/stanford_profile_helper/stanford_profile_helper.module
  tests/codeception/acceptance/Content/PersonCest.php
  themes/stanford_basic/dist/assets/fonts/fa-brands-400.eot
  themes/stanford_basic/dist/assets/fonts/fa-brands-400.ttf
  themes/stanford_basic/dist/assets/fonts/fa-brands-400.woff
  themes/stanford_basic/dist/assets/fonts/fa-brands-400.woff2
  themes/stanford_basic/dist/assets/fonts/fa-regular-400.eot
  themes/stanford_basic/dist/assets/fonts/fa-regular-400.ttf
  themes/stanford_basic/dist/assets/fonts/fa-regular-400.woff
  themes/stanford_basic/dist/assets/fonts/fa-regular-400.woff2
  themes/stanford_basic/dist/assets/fonts/fa-solid-900.eot
  themes/stanford_basic/dist/assets/fonts/fa-solid-900.ttf
  themes/stanford_basic/dist/assets/fonts/fa-solid-900.woff
  themes/stanford_basic/dist/assets/fonts/fa-solid-900.woff2
  themes/stanford_basic/dist/assets/svg/fa-brands-400.svg
  themes/stanford_basic/dist/assets/svg/fa-regular-400.svg
  themes/stanford_basic/dist/assets/svg/fa-solid-900.svg
  themes/stanford_basic/dist/css/layout.css
  themes/stanford_basic/dist/js/base.js
  themes/stanford_basic/dist/js/base.js.map
  themes/stanford_basic/dist/js/behaviors.js
  themes/stanford_basic/dist/js/behaviors.js.map
  themes/stanford_basic/dist/templates/decanter/components/global-footer/global-footer.twig
  themes/stanford_basic/src/scss/layout/_page.scss
  themes/stanford_basic/stanford_basic.theme
  themes/stanford_basic/templates/views/views-view-list--taxonomy-term-pages--people-terms.html.twig
  themes/stanford_basic/yarn.lock
Labels: size/xl

#622 Revert composer.json
  composer.json
Labels: size/xs
