Repository SU-SWS/stanford_profile, pull requests merged in 2022-10, with the labels that each got.

#624 Added view to display policy child pages
  config/sync/core.entity_form_display.paragraph.stanford_accordion.default.yml
  config/sync/core.entity_form_display.paragraph.stanford_banner.default.yml
  config/sync/core.entity_form_display.paragraph.stanford_card.default.yml
  config/sync/core.entity_form_display.paragraph.stanford_entity.default.yml
  config/sync/core.entity_form_display.paragraph.stanford_gallery.default.yml
  config/sync/core.entity_form_display.paragraph.stanford_lists.default.yml
  config/sync/core.entity_form_display.paragraph.stanford_media_caption.default.yml
  config/sync/core.entity_form_display.paragraph.stanford_person_cta.default.yml
  config/sync/core.entity_form_display.paragraph.stanford_schedule.default.yml
  config/sync/core.entity_form_display.paragraph.stanford_spacer.default.yml
  config/sync/core.entity_form_display.paragraph.stanford_wysiwyg.default.yml
  config/sync/core.entity_view_display.node.stanford_policy.default.yml
  config/sync/core.entity_view_display.node.stanford_policy.teaser.yml
  config/sync/views.view.policies.yml
Labels: size/s

#626 Modify directory permissions when copying the file during install
  composer.json
  src/EventSubscriber/EventSubscriber.php
Labels: size/xs

#619 D8CORE-5250 Add "Last Updated" to search results items
  config/sync/views.view.search.yml
  tests/codeception/acceptance/Content/BasicPageCest.php
Labels: size/s

#629 D8CORE-6312 Fix node title not reflecting the changes
  config/sync/migrate_plus.migration.stanford_localist_importer.yml
  config/sync/search_api.index.full_site_content.yml
  config/sync/views.view.search.yml
  modules/stanford_policy/src/EventSubscriber/StanfordPolicySubscriber.php
  modules/stanford_policy/tests/src/Kernel/EventSubscriber/StanfordPolicySubscriberTest.php
  tests/codeception/acceptance/Content/PersonCest.php
  tests/codeception/acceptance/Content/PolicyCest.php
Labels: size/xs

#630 Added Fast 404 module
  composer.json
  config/sync/core.extension.yml
  config/sync/ultimate_cron.job.fast_404_generator_cron.yml
Labels: size/xs

#623 D8CORE-6251: Added a toggle in the theme to turn off the external links
  config/sync/core.entity_form_display.config_pages.stanford_basic_site_settings.default.yml
  config/sync/core.entity_view_display.config_pages.stanford_basic_site_settings.default.yml
  config/sync/field.field.config_pages.stanford_basic_site_settings.su_hide_ext_link_icons.yml
  config/sync/field.storage.config_pages.su_hide_ext_link_icons.yml
  content/config_pages/0d7e973e-6b97-4243-a373-d486a581eb84.yml
  modules/stanford_profile_styles/stanford_profile_styles.module
  src/Plugin/InstallTask/SiteSettings.php
  tests/codeception/functional/Contrib/ExtLinkCest.php
Labels: size/s

#628 D8CORE-6304: layout and style set up for Policy
  config/sync/core.entity_view_display.node.stanford_policy.default.yml
  config/sync/views.view.change_logs.yml
  config/sync/views.view.policies.yml
  themes/stanford_basic/dist/css/content/policy.css
  themes/stanford_basic/dist/js/base.js
  themes/stanford_basic/dist/js/base.js.map
  themes/stanford_basic/dist/js/behaviors.js
  themes/stanford_basic/dist/js/behaviors.js.map
  themes/stanford_basic/package-lock.json
  themes/stanford_basic/src/scss/content/policy/_policy.scss
  themes/stanford_basic/src/scss/content/policy/index.scss
  themes/stanford_basic/stanford_basic.libraries.yml
  themes/stanford_basic/stanford_basic.theme
  themes/stanford_basic/templates/field/field--default--node-title--stanford-policy.html.twig
  themes/stanford_basic/templates/field/field--su-policy-related.html.twig
  themes/stanford_basic/webpack.config.js
Labels: size/xl

#631 D8CORE-3498: Added additional contact information field
  config/sync/core.entity_form_display.node.stanford_event.default.yml
  config/sync/core.entity_view_display.node.stanford_event.default.yml
  config/sync/core.entity_view_display.node.stanford_event.search_indexing.yml
  config/sync/core.entity_view_display.node.stanford_event.stanford_card.yml
  config/sync/core.entity_view_display.node.stanford_event.teaser.yml
  config/sync/field.field.node.stanford_event.su_event_contact_info.yml
  config/sync/field.storage.node.su_event_contact_info.yml
  modules/stanford_events/dist/css/stanford_events.node.css
  modules/stanford_events/dist/js/stanford_events.node.behaviors.js.map
  modules/stanford_events/lib/scss/stanford_events.node.scss
  tests/codeception/acceptance/Content/EventsCest.php
Labels: size/s

#632 D8CORE-6325 Set the active item on book side navigation
  .circleci/config.yml
  .github/workflows/back-to-dev.yml
  .github/workflows/tests.yml
  themes/stanford_basic/stanford_basic.theme
Labels: size/s

#633 D8CORE-6323: adding styling for change log block anywhere
  themes/stanford_basic/dist/css/content/policy.css
  themes/stanford_basic/dist/css/print.css
  themes/stanford_basic/src/scss/content/policy/_policy.scss
  themes/stanford_basic/src/scss/print/_print.scss
  themes/stanford_basic/stanford_basic.theme
Labels: size/xs

#634 D8CORE-6327: fix to the related cards for mobile
  themes/stanford_basic/dist/css/content/policy.css
  themes/stanford_basic/src/scss/content/policy/_policy.scss
Labels: size/xs

#635 D8CORE-6329: unique ids for prev/next buttons
  themes/stanford_basic/templates/navigation/book-navigation.html.twig
Labels: size/xs

#636 D8CORE-6330: moved the back and forward button for mobile
  config/sync/core.entity_view_display.node.stanford_policy.default.yml
  themes/stanford_basic/dist/css/content/policy.css
  themes/stanford_basic/src/scss/content/policy/_policy.scss
Labels: size/xs

#638 D8CORE-6237: Corrected courses migration
  config/sync/migrate_plus.migration.stanford_courses.yml
Labels: size/xs
