Repository SU-SWS/stanford_profile, pull requests merged in 2023-07, with the labels that each got.

#684 D8CORE-6804 | @jdwjdwjdw | Fix minimally-branded subtheme publications teaser link colors
  themes/minimally_branded_subtheme/dist/css/minimally_branded_subtheme.css
  themes/minimally_branded_subtheme/dist/js/scripts.js.map
  themes/minimally_branded_subtheme/src/scss/theme/_link.scss
Labels: size/xs

#685 10.0.1
  CHANGELOG.md
  config/sync/field.field.node.stanford_event.su_event_components.yml
  config/sync/field.field.node.stanford_event_series.su_event_series_components.yml
  config/sync/field.field.node.stanford_news.su_news_components.yml
  config/sync/field.field.node.stanford_person.su_person_components.yml
  config/sync/field.field.node.stanford_publication.su_publication_components.yml
  stanford_profile.info.yml
  themes/minimally_branded_subtheme/dist/css/minimally_branded_subtheme.css
  themes/minimally_branded_subtheme/dist/js/scripts.js.map
  themes/minimally_branded_subtheme/src/scss/theme/_link.scss
  themes/stanford_basic/stanford_basic.theme
Labels: patch, size/xs

#686 10.0.2
  CHANGELOG.md
  config/sync/jsonapi_extras.jsonapi_resource_config.user--user.yml
  stanford_profile.info.yml
  stanford_profile.install
Labels: patch, size/s

#688 Adjust test to run a little faster
  tests/codeception/acceptance/Contrib/NodeRevisionDeleteCest.php
Labels: size/xs

#691 Add system test
  .github/workflows/tests.yml
  composer.json
  config/sync/chosen.settings.yml
  config/sync/node.type.stanford_policy.yml
  config/sync/xmlsitemap.settings.node.stanford_policy.yml
  config/sync/xmlsitemap.settings.yml
  tests/codeception/acceptance/SystemCest.php
Labels: size/xs

#692 10.0.3
  .github/workflows/tests.yml
  CHANGELOG.md
  composer.json
  config/sync/chosen.settings.yml
  config/sync/google_tag.settings.yml
  config/sync/node.type.stanford_policy.yml
  config/sync/user.role.site_manager.yml
  config/sync/xmlsitemap.settings.node.stanford_policy.yml
  config/sync/xmlsitemap.settings.yml
  stanford_profile.info.yml
  stanford_profile.install
  tests/codeception/acceptance/Contrib/NodeRevisionDeleteCest.php
  tests/codeception/acceptance/SystemCest.php
  themes/stanford_basic/decoupled-menu/.nvmrc
  themes/stanford_basic/decoupled-menu/dist/islands/main-menu.island.umd.js
  themes/stanford_basic/decoupled-menu/src/main-menu.island.tsx
  themes/stanford_basic/decoupled-menu/yarn.lock
Labels: patch, size/l

#693 10.0.4
  CHANGELOG.md
  stanford_profile.info.yml
  stanford_profile.post_update.php
  tests/codeception/acceptance/SystemCest.php
Labels: patch, size/xs
