Repository SU-SWS/stanford_profile, pull requests merged in 2023-09, with the labels that each got.

#703 D8CORE-6844 | @jdwjdwjdw | Fixup mobile menu at medium breakpoint
  themes/stanford_basic/dist/css/components.css
  themes/stanford_basic/package-lock.json
  themes/stanford_basic/src/scss/components/masthead/_wrapper.scss
  themes/stanford_basic/src/scss/components/multi-menu/_multi-menu.scss
Labels: size/xs

#694 D8CORE-6843: Update bad user guide links in help text
  config/sync/field.field.config_pages.lockup_settings.su_lockup_enabled.yml
  config/sync/field.field.config_pages.stanford_global_message.su_global_msg_type.yml
  config/sync/field.field.config_pages.stanford_local_footer.su_local_foot_use_loc.yml
  config/sync/field.field.node.stanford_event.su_event_type.yml
  config/sync/field.field.node.stanford_news.su_news_topics.yml
  config/sync/field.field.node.stanford_publication.su_publication_citation.yml
  config/sync/field.field.node.stanford_publication.su_publication_topics.yml
  config/sync/field.field.paragraph.stanford_entity.su_entity_item.yml
  config/sync/field.field.paragraph.stanford_lists.su_list_view.yml
  config/sync/migrate_plus.migration.stanford_publications.yml
  src/Plugin/HelpSection/ProfileHelpSection.php
Labels: patch, size/xs

#690 D8CORE-4551: updated permissions for contributors and site editors
  config/sync/user.role.contributor.yml
  config/sync/user.role.site_editor.yml
  config/sync/user.role.su_site_embedder.yml
  tests/codeception/acceptance/Content/EventsSeriesCest.php
  tests/codeception/acceptance/Content/PolicyCest.php
  tests/codeception/acceptance/Media/MediaPermissionsCest.php
  tests/codeception/acceptance/Users/RolesCest.php
Labels: size/xs

#709 Use components field instead of layout builder for list pages
  content/node/0b83d1e9-688a-4475-9673-a4c385f26247.yml
  content/node/14768832-f763-4d27-8df6-7cd784886d57.yml
  content/node/673a8fb8-39ac-49df-94c2-ed8d04db16a7.yml
  content/node/72f0069b-f1ec-4122-af73-6aa841faea90.yml
  content/node/8ba98fcf-d390-4014-92de-c77a59b30f3b.yml
  content/node/bc484600-a21a-4497-b9f7-f928474b511c.yml
  content/node/d21d84f0-22e7-4596-82cb-9209841a3276.yml
  content/node/e18a741f-7d86-492a-a02f-7ca73989ca13.yml
  tests/codeception/acceptance/Content/EventsCest.php
Labels: size/s

#712 10.1.0
  .github/workflows/release.yml
  CHANGELOG.md
  stanford_profile.info.yml
Labels: size/xs, minor

#713 Update samlauth settings when a role is created or deleted
  config/sync/config_ignore.settings.yml
  config/sync/user.role.site_manager.yml
  src/EventSubscriber/EventSubscriber.php
  stanford_profile.post_update.php
  tests/src/Kernel/EventSubscriber/EventSubscriberTest.php
Labels: size/xs

#714 10.1.1
  CHANGELOG.md
  stanford_profile.info.yml
Labels: patch, size/xs

#715 10.1.2
  CHANGELOG.md
  config/sync/config_pages.type.stanford_saml.yml
  stanford_profile.info.yml
Labels: patch, size/xs
