Repository SU-SWS/stanford_profile, pull requests merged in 2023-11, with the labels that each got.

#728 D8CORE-2761: reduced padding on filterby menu
  themes/stanford_basic/dist/css/components.css
  themes/stanford_basic/src/scss/components/filter-menu/_filter-menu.scss
Labels: patch, size/xs

#744 D8CORE-7056 | @jdwjdwjdw | Update alert styles
  themes/stanford_basic/dist/css/components.css
  themes/stanford_basic/src/scss/components/alert/_alert--info.scss
Labels: size/xs

#746 D8CORE-6726: Overrode the colorbox formatter template to remove aria-label
  src/EventSubscriber/EventSubscriber.php
  tests/codeception/functional/Paragraphs/GalleryCest.php
  tests/src/Kernel/EventSubscriber/EventSubscriberTest.php
  themes/stanford_basic/templates/contrib/colorbox-formatter.html.twig
Labels: size/xs

#743 D8CORE-7074 Implement Search API Algolia
  composer.json
  config/sync/config_pages.type.stanford_basic_site_settings.yml
  config/sync/core.entity_form_display.config_pages.stanford_basic_site_settings.default.yml
  config/sync/core.entity_view_display.config_pages.stanford_basic_site_settings.default.yml
  config/sync/core.extension.yml
  config/sync/editoria11y.settings.yml
  config/sync/field.field.config_pages.stanford_basic_site_settings.su_site_algolia.yml
  config/sync/field.field.config_pages.stanford_basic_site_settings.su_site_algolia_file.yml
  config/sync/field.field.config_pages.stanford_basic_site_settings.su_site_algolia_id.yml
  config/sync/field.field.config_pages.stanford_basic_site_settings.su_site_algolia_index.yml
  config/sync/field.field.config_pages.stanford_basic_site_settings.su_site_algolia_key.yml
  config/sync/field.field.config_pages.stanford_basic_site_settings.su_site_algolia_search.yml
  config/sync/field.storage.config_pages.su_site_algolia.yml
  config/sync/field.storage.config_pages.su_site_algolia_file.yml
  config/sync/field.storage.config_pages.su_site_algolia_id.yml
  config/sync/field.storage.config_pages.su_site_algolia_index.yml
  config/sync/field.storage.config_pages.su_site_algolia_key.yml
  config/sync/field.storage.config_pages.su_site_algolia_search.yml
  config/sync/field_validation.rule_set.config_pages_stanford_basic_site_settings.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.config_pages--stanford_basic_site_settings.yml
  config/sync/search_api.index.algolia_search.yml
  config/sync/search_api.index.full_site_content.yml
  config/sync/search_api.server.algolia_search.yml
  config/sync/search_api_algolia.settings.yml
  config/sync/views.view.search.yml
  src/Config/ConfigOverrides.php
  themes/stanford_basic/algolia-search/.env
  themes/stanford_basic/algolia-search/.gitignore
  themes/stanford_basic/algolia-search/.nvmrc
  themes/stanford_basic/algolia-search/dist/index.html
  themes/stanford_basic/algolia-search/dist/islands/algolia-search.island.js
  themes/stanford_basic/algolia-search/dist/islands/algolia-search.island.js.LICENSE.txt
  themes/stanford_basic/algolia-search/package.json
  themes/stanford_basic/algolia-search/src/algolia-search.island.tsx
  themes/stanford_basic/algolia-search/src/hits/default-hit.tsx
  themes/stanford_basic/algolia-search/src/hits/events.tsx
  themes/stanford_basic/algolia-search/src/hits/news.tsx
  themes/stanford_basic/algolia-search/src/search-box.tsx
  themes/stanford_basic/algolia-search/src/template.html
  themes/stanford_basic/algolia-search/tsconfig.json
  themes/stanford_basic/algolia-search/webpack.config.js
  themes/stanford_basic/algolia-search/yarn.lock
  themes/stanford_basic/stanford_basic.libraries.yml
  themes/stanford_basic/stanford_basic.theme
Labels: size/xl

#748 Update github actions
  .github/workflows/tests.yml
Labels: size/xs

#747 D8CORE-7096 | @jdwjdwjdw | Update algolia search results styles and structure
  themes/stanford_basic/algolia-search/dist/islands/algolia-search.island.js
  themes/stanford_basic/algolia-search/src/algolia-search.island.tsx
  themes/stanford_basic/algolia-search/src/hits/default-hit.tsx
  themes/stanford_basic/algolia-search/src/search-box.tsx
Labels: size/xs
