Repository SU-SWS/stanford_profile, pull requests merged in 2023-06, with the labels that each got.

#667 D8CORE-6654 | @jdwjdwjdw | Update stanford_basic package-lock
  themes/stanford_basic/dist/assets/fonts/fa-brands-400.eot
  themes/stanford_basic/dist/assets/fonts/fa-brands-400.ttf
  themes/stanford_basic/dist/assets/fonts/fa-brands-400.woff
  themes/stanford_basic/dist/assets/fonts/fa-brands-400.woff2
  themes/stanford_basic/dist/assets/fonts/fa-regular-400.eot
  themes/stanford_basic/dist/assets/fonts/fa-regular-400.ttf
  themes/stanford_basic/dist/assets/fonts/fa-regular-400.woff
  themes/stanford_basic/dist/assets/fonts/fa-regular-400.woff2
  themes/stanford_basic/dist/assets/fonts/fa-solid-900.eot
  themes/stanford_basic/dist/assets/fonts/fa-solid-900.ttf
  themes/stanford_basic/dist/assets/fonts/fa-solid-900.woff
  themes/stanford_basic/dist/assets/fonts/fa-solid-900.woff2
  themes/stanford_basic/dist/assets/svg/fa-brands-400.svg
  themes/stanford_basic/dist/assets/svg/fa-regular-400.svg
  themes/stanford_basic/dist/assets/svg/fa-solid-900.svg
  themes/stanford_basic/dist/css/base.css
  themes/stanford_basic/dist/js/base.js
  themes/stanford_basic/dist/js/base.js.map
  themes/stanford_basic/dist/js/behaviors.js
  themes/stanford_basic/dist/js/behaviors.js.map
  themes/stanford_basic/dist/templates/decanter/components/brand-bar/brand-bar.twig
  themes/stanford_basic/dist/templates/decanter/components/global-footer/global-footer.twig
  themes/stanford_basic/dist/templates/decanter/components/logo/logo.twig
  themes/stanford_basic/package-lock.json
Labels: size/xl

#665 D8CORE-2622, D8CORE-4494 | @jdwjdwjdw | Move brand bar and skip-links into header landmark banner
  themes/stanford_basic/templates/html.html.twig
  themes/stanford_basic/templates/page.html.twig
Labels: size/xs

#662 D8CORE-000 | @jdwjdwjdw | Fix policy typo
  config/sync/field.field.node.stanford_policy.su_policy_effective.yml
Labels: size/xs

#663 Replace menu with a decoupled main menu
  config/sync/core.entity_form_display.config_pages.stanford_basic_site_settings.default.yml
  config/sync/core.entity_view_display.config_pages.stanford_basic_site_settings.default.yml
  config/sync/field.field.config_pages.stanford_basic_site_settings.su_site_new_menu.yml
  config/sync/field.field.config_pages.stanford_basic_site_settings.su_site_nobots.yml
  config/sync/field.storage.config_pages.su_site_new_menu.yml
  config/sync/field.storage.config_pages.su_site_nobots.yml
  themes/stanford_basic/decoupled-menu/.env
  themes/stanford_basic/decoupled-menu/.gitignore
  themes/stanford_basic/decoupled-menu/.nvmrc
  themes/stanford_basic/decoupled-menu/.prettierrc
  themes/stanford_basic/decoupled-menu/FileSizePlugin.js
  themes/stanford_basic/decoupled-menu/dist/index.html
  themes/stanford_basic/decoupled-menu/dist/islands/main-menu.island.umd.js
  themes/stanford_basic/decoupled-menu/dist/islands/main-menu.island.umd.js.LICENSE.txt
  themes/stanford_basic/decoupled-menu/package.json
  themes/stanford_basic/decoupled-menu/playwright.config.ts
  themes/stanford_basic/decoupled-menu/src/components/caret.tsx
  themes/stanford_basic/decoupled-menu/src/components/close.tsx
  themes/stanford_basic/decoupled-menu/src/components/hamburger.tsx
  themes/stanford_basic/decoupled-menu/src/components/magnifying-glass.tsx
  themes/stanford_basic/decoupled-menu/src/components/outside-click-handler.tsx
  themes/stanford_basic/decoupled-menu/src/config/env.ts
  themes/stanford_basic/decoupled-menu/src/global.d.ts
  themes/stanford_basic/decoupled-menu/src/hooks/useWebComponentEvents.ts
  themes/stanford_basic/decoupled-menu/src/main-menu.island.tsx
  themes/stanford_basic/decoupled-menu/src/tools/build-menu-tree.tsx
  themes/stanford_basic/decoupled-menu/src/tools/deserialize.tsx
  themes/stanford_basic/decoupled-menu/tsconfig.json
  themes/stanford_basic/decoupled-menu/webpack.config.js
  themes/stanford_basic/decoupled-menu/yarn.lock
  themes/stanford_basic/dist/css/components.css
  themes/stanford_basic/dist/css/layout.css
  themes/stanford_basic/src/scss/components/masthead/_wrapper.scss
  themes/stanford_basic/src/scss/components/multi-menu/_multi-menu.scss
  themes/stanford_basic/src/scss/layout/_page.scss
  themes/stanford_basic/stanford_basic.libraries.yml
  themes/stanford_basic/stanford_basic.theme
  themes/stanford_basic/templates/block/block--system-menu-block--main.html.twig
Labels: size/xl

#670 9.2.6
  .github/workflows/release.yml
  CHANGELOG.md
  composer.json
  config/sync/core.entity_view_display.node.stanford_policy.stanford_card.yml
  config/sync/core.entity_view_display.node.stanford_policy.teaser.yml
  config/sync/field.field.node.stanford_policy.su_policy_effective.yml
  config/sync/stanford_ssp.settings.yml
  config/sync/user.role.anonymous.yml
  config/sync/user.role.authenticated.yml
  config/sync/user.role.contributor.yml
  config/sync/user.role.layout_builder_user.yml
  config/sync/user.role.site_builder.yml
  config/sync/user.role.site_developer.yml
  config/sync/user.role.site_editor.yml
  config/sync/user.role.site_manager.yml
  stanford_profile.info.yml
  tests/codeception/acceptance/Content/BasicPageCest.php
  tests/codeception/acceptance/Content/PublicationsCest.php
  tests/codeception/acceptance/Contrib/ViewsBulkEditCest.php
  tests/codeception/acceptance/Media/MediaCest.php
  tests/codeception/acceptance/Paragraphs/ListsCest.php
  tests/src/Kernel/Plugin/InstallTask/SiteSettingsTest.php
  themes/stanford_basic/dist/assets/fonts/fa-brands-400.eot
  themes/stanford_basic/dist/assets/fonts/fa-brands-400.ttf
  themes/stanford_basic/dist/assets/fonts/fa-brands-400.woff
  themes/stanford_basic/dist/assets/fonts/fa-brands-400.woff2
  themes/stanford_basic/dist/assets/fonts/fa-regular-400.eot
  themes/stanford_basic/dist/assets/fonts/fa-regular-400.ttf
  themes/stanford_basic/dist/assets/fonts/fa-regular-400.woff
  themes/stanford_basic/dist/assets/fonts/fa-regular-400.woff2
  themes/stanford_basic/dist/assets/fonts/fa-solid-900.eot
  themes/stanford_basic/dist/assets/fonts/fa-solid-900.ttf
  themes/stanford_basic/dist/assets/fonts/fa-solid-900.woff
  themes/stanford_basic/dist/assets/fonts/fa-solid-900.woff2
  themes/stanford_basic/dist/assets/svg/fa-brands-400.svg
  themes/stanford_basic/dist/assets/svg/fa-regular-400.svg
  themes/stanford_basic/dist/assets/svg/fa-solid-900.svg
  themes/stanford_basic/dist/css/base.css
  themes/stanford_basic/dist/css/content/policy.css
  themes/stanford_basic/dist/js/base.js
  themes/stanford_basic/dist/js/base.js.map
  themes/stanford_basic/dist/js/behaviors.js
  themes/stanford_basic/dist/js/behaviors.js.map
  themes/stanford_basic/dist/templates/decanter/components/brand-bar/brand-bar.twig
  themes/stanford_basic/dist/templates/decanter/components/global-footer/global-footer.twig
  themes/stanford_basic/dist/templates/decanter/components/logo/logo.twig
  themes/stanford_basic/package-lock.json
  themes/stanford_basic/src/scss/content/policy/_policy.scss
  themes/stanford_basic/templates/html.html.twig
  themes/stanford_basic/templates/page.html.twig
Labels: patch, size/xl

#672 D8CORE-5407 | @jdwjdwjdw | A11y: Update lockup cell2 max-width, line3 line-height
  themes/stanford_basic/dist/css/components.css
  themes/stanford_basic/src/scss/components/lockup/_lockup.scss
Labels: size/xs

#674 D8CORE-6731 | @jdwjdwjdw | Move help section to be below brand bar in header
  themes/stanford_basic/templates/page.html.twig
Labels: size/xs

#675 9.2.7
  CHANGELOG.md
  stanford_profile.info.yml
  themes/stanford_basic/templates/page.html.twig
Labels: patch, size/xs

#676 9.2.8
  CHANGELOG.md
  stanford_profile.info.yml
  themes/stanford_basic/stanford_basic.theme
Labels: patch, size/xs

#678 Update metatag module and config
  composer.json
  config/sync/metatag.metatag_defaults.front.yml
  config/sync/metatag.metatag_defaults.node.yml
  config/sync/metatag.metatag_defaults.node__stanford_news.yml
  config/sync/metatag.metatag_defaults.node__stanford_person.yml
Labels: size/xs

#677 D8CORE-6695, 6694 Updated spacer paragraph with optional sizes
  config/sync/core.entity_form_display.paragraph.stanford_spacer.default.yml
  config/sync/core.entity_view_display.paragraph.stanford_spacer.default.yml
  config/sync/field.field.paragraph.stanford_spacer.su_spacer_size.yml
  config/sync/field.storage.paragraph.su_spacer_size.yml
  tests/codeception/functional/Paragraphs/SpacerCest.php
  themes/stanford_basic/dist/css/components.css
  themes/stanford_basic/src/scss/components/all/_vertical-spacing.scss
  themes/stanford_basic/src/scss/components/all/index.scss
  themes/stanford_basic/src/scss/components/index.scss
  themes/stanford_basic/src/scss/components/spacer/_spacer.scss
  themes/stanford_basic/src/scss/components/spacer/index.scss
  themes/stanford_basic/stanford_basic.theme
Labels: patch, size/s

#680 D8CORE-4365 | @jdwjdwjdw | Update banner aspect ratio for small breakpoint
  themes/stanford_basic/dist/css/components.css
  themes/stanford_basic/src/scss/components/hero/_hero.scss
  themes/stanford_basic/src/scss/components/hero/_index.scss
  themes/stanford_basic/src/scss/components/index.scss
Labels: size/xs

#681 D8CORE-6633 Add skip link anchor to the search page
  config/sync/block.block.minimally_branded_subtheme_main_anchor.yml
  config/sync/block.block.stanford_basic_main_anchor.yml
  stanford_profile.post_update.php
  tests/codeception/acceptance/Content/BasicPageCest.php
Labels: size/xs

#679 D8CORE-6760 | @jdwjdwjdw | Update ckeditor5 styles
  themes/stanford_basic/dist/css/ckeditor5.css
  themes/stanford_basic/src/scss/ckeditor5.scss
Labels: size/s

#682 Updating to new decanter version
  themes/stanford_basic/dist/css/base.css
  themes/stanford_basic/dist/css/ckeditor.css
  themes/stanford_basic/dist/css/ckeditor5.css
  themes/stanford_basic/dist/templates/decanter/components/global-footer/global-footer.twig
  themes/stanford_basic/dist/templates/decanter/components/logo/logo.twig
  themes/stanford_basic/package-lock.json
  themes/stanford_basic/package.json
Labels: size/xs
