Repository SU-SWS/stanford_profile, pull requests merged in 2023-10, with the labels that each got.

#721 D8CORE-6977 Switch to use CSHS instead of simple heiracry select
  config/sync/core.entity_form_display.media.file.default.yml
  config/sync/core.entity_form_display.media.file.media_library.yml
  config/sync/core.entity_form_display.media.image.default.yml
  config/sync/core.entity_form_display.media.image.media_library.yml
  config/sync/core.entity_form_display.media.stanford_gallery_images.default.yml
  config/sync/core.entity_form_display.media.stanford_gallery_images.media_library.yml
  config/sync/core.entity_form_display.media.video.default.yml
  config/sync/core.entity_form_display.media.video.media_library.yml
  config/sync/core.entity_form_display.node.stanford_course.default.yml
  config/sync/core.entity_form_display.node.stanford_event.default.yml
  config/sync/core.entity_form_display.node.stanford_event_series.default.yml
  config/sync/core.entity_form_display.node.stanford_news.default.yml
  config/sync/core.entity_form_display.node.stanford_page.default.yml
  config/sync/core.entity_form_display.node.stanford_person.default.yml
  config/sync/core.entity_form_display.node.stanford_publication.default.yml
  config/sync/google_analytics.settings.yml
  tests/codeception/acceptance/Content/BasicPageCest.php
  tests/codeception/acceptance/Content/EventsCest.php
  tests/codeception/acceptance/Content/PersonCest.php
  tests/codeception/acceptance/Content/PublicationsCest.php
  tests/codeception/acceptance/Contrib/ViewsBulkEditCest.php
  tests/codeception/acceptance/Paragraphs/ListsCest.php
  tests/codeception/functional/Content/StanfordNewsCest.php
Labels: size/s

#722 D8CORE-6953: Additional edits to the editing buttons
  themes/stanford_basic/dist/css/theme.css
  themes/stanford_basic/src/scss/theme/menu/_local-tasks.scss
Labels: size/xs

#719 D8CORE-6952: changed to list style none
  themes/stanford_basic/dist/css/components.css
  themes/stanford_basic/src/scss/components/filter-menu/_filter-menu.scss
Labels: size/xs

#723 D8CORE-6951 | @jdwjdwjdw | D10 Clean up admin toolbar
  themes/stanford_basic/dist/css/admin.css
  themes/stanford_basic/dist/js/base.js.map
  themes/stanford_basic/src/scss/admin/_menu.scss
Labels: size/xs

#724 SDSS-1007: Add support for global footer variant.
  themes/stanford_basic/config/install/stanford_basic.settings.yml
  themes/stanford_basic/stanford_basic.theme
  themes/stanford_basic/templates/page.html.twig
  themes/stanford_basic/theme-settings.php
Labels: size/xs

#727 D8CORE-6974 | @jdwjdwjdw | Update local footer config userguide links
  config/sync/field.field.config_pages.stanford_local_footer.su_local_foot_help.yml
  config/sync/field.field.config_pages.stanford_local_footer.su_local_foot_use_loc.yml
Labels: size/xs

#729 Update config ignore settings for latest module
  config/sync/config_ignore.settings.yml
Labels: size/xs

#730 D8CORE-6976: updated to newest decanter
  themes/stanford_basic/dist/css/base.css
  themes/stanford_basic/dist/css/ckeditor.css
  themes/stanford_basic/package.json
  themes/stanford_basic/yarn.lock
Labels: size/xs

#732 11.0.0
  CHANGELOG.md
  src/EventSubscriber/EventSubscriber.php
  stanford_profile.info.yml
Labels: size/xs, major

#733 11.0.1
  CHANGELOG.md
  stanford_profile.info.yml
Labels: patch, size/xs

#734 Adjust acceptance tests
  CHANGELOG.md
  config/sync/core.entity_form_display.config_pages.stanford_basic_site_settings.default.yml
  stanford_profile.info.yml
  tests/codeception/acceptance/Content/BasicPageCest.php
  tests/codeception/acceptance/Content/CoursesCest.php
  tests/codeception/acceptance/Content/CustomBlockCest.php
  tests/codeception/acceptance/Content/EventsCest.php
  tests/codeception/acceptance/Content/NewsCest.php
  tests/codeception/acceptance/Content/PersonCest.php
  tests/codeception/acceptance/Content/PolicyCest.php
  tests/codeception/acceptance/Content/PublicationsCest.php
  tests/codeception/acceptance/Content/SearchBlockCest.php
  tests/codeception/acceptance/Contrib/ViewsBulkEditCest.php
  tests/codeception/acceptance/GlobalMessage/GlobalMessageCest.php
  tests/codeception/acceptance/HomePageCest.php
  tests/codeception/acceptance/LocalFooter/LocalFooterCest.php
  tests/codeception/acceptance/LocalFooter/LocalFooterLockupCest.php
  tests/codeception/acceptance/LockupSettings/LockupSettingsCest.php
  tests/codeception/acceptance/Media/MediaCest.php
  tests/codeception/acceptance/Media/MediaFormsCest.php
  tests/codeception/acceptance/Paragraphs/Issue2901390Cest.php
  tests/codeception/acceptance/Paragraphs/ListsCest.php
  tests/codeception/acceptance/SubThemeCest.php
  tests/codeception/acceptance/SuperFooter/SuperFooterCest.php
  tests/codeception/acceptance/SystemSiteConfigCest.php
  tests/codeception/acceptance/TextFormatsCest.php
  tests/codeception/acceptance/Users/IntranetCest.php
  tests/codeception/acceptance/Users/RolesCest.php
  tests/codeception/functional/Content/BasicPageParagraphsCest.php
  tests/codeception/functional/Content/StanfordNewsCest.php
  tests/codeception/functional/Contrib/ExtLinkCest.php
  tests/codeception/functional/Navigation/NavigationDropDownsCest.php
  tests/codeception/functional/Paragraphs/EntityReferenceCest.php
  tests/codeception/functional/Paragraphs/GalleryCest.php
  tests/codeception/functional/Paragraphs/SpacerCest.php
  tests/codeception/functional/Paragraphs/WYSIWYGCest.php
  tests/codeception/functional/Users/RolesCest.php
Labels: patch, size/s

#735 Next site settings and config ignores
  config/sync/config_ignore.settings.yml
  config/sync/next.settings.yml
  config/sync/user.role.decoupled_site_users.yml
  tests/codeception/acceptance/Content/PersonCest.php
  tests/codeception/acceptance/Paragraphs/ListsCest.php
Labels: size/xs

#736 11.0.3
  CHANGELOG.md
  stanford_profile.info.yml
Labels: patch, size/xs

#737 D8CORE-7051 Use display field copy instead of token fields
  config/sync/core.entity_form_display.config_pages.stanford_basic_site_settings.default.yml
  config/sync/core.entity_view_display.node.stanford_event.stanford_card.yml
  config/sync/core.entity_view_display.node.stanford_event.teaser.yml
  config/sync/ds.field.basic_page_type_content_url.yml
  config/sync/ds.field.date_end_day.yml
  config/sync/ds.field.date_end_month.yml
  config/sync/ds.field.event_date_time_1.yml
  config/sync/ds.field.event_date_time_2.yml
  config/sync/ds.field.event_date_time_3.yml
  config/sync/ds.field.event_date_time_4.yml
  config/sync/ds.field.event_start_day.yml
  config/sync/ds.field.event_start_month.yml
  config/sync/field.storage.config_pages.su_site_org.yml
  config/sync/smart_date.smart_date_format.day.yml
  config/sync/smart_date.smart_date_format.short_month.yml
  content/taxonomy_term/0041f7fa-7608-4a39-9165-eb0fb9c592d5.yml
  content/taxonomy_term/04a17e8e-a333-47ca-b5db-9d5989cbae8e.yml
  content/taxonomy_term/1f588611-ddcd-4cca-b057-4cbcc1f791ae.yml
  content/taxonomy_term/32028190-0690-423e-ba2a-723b0af0febb.yml
  content/taxonomy_term/33b947db-a1d0-4063-ba6a-bec47bc4e006.yml
  content/taxonomy_term/35a291b2-8f74-4bb8-bc62-39e21c80e77c.yml
  content/taxonomy_term/3a4ad061-c28c-4125-9183-6ae995038f3f.yml
  content/taxonomy_term/46cb7fbc-27f1-483a-99b4-867600410138.yml
  content/taxonomy_term/495440e1-742e-445f-8b77-9a972ecb82ff.yml
  content/taxonomy_term/55627a30-9032-44d6-aca9-aa43fc037c1e.yml
  content/taxonomy_term/5d9e72d5-45b1-43ab-afae-f1e5bd55007f.yml
  content/taxonomy_term/5e07046b-302f-45c7-a46d-17350cbe001d.yml
  content/taxonomy_term/5f6ea0cd-520a-4c99-a826-592ea9c8330c.yml
  content/taxonomy_term/62bbda38-57a5-47e4-8c36-c70ea9f70f30.yml
  content/taxonomy_term/62deaa58-ec4c-41e2-8681-d0e95965ea9d.yml
  content/taxonomy_term/6940df7a-2ad4-4a64-93a8-8218a64e8169.yml
  content/taxonomy_term/6fa0ffd2-ceda-4598-80c0-ed01c53b0b94.yml
  content/taxonomy_term/72272279-9f82-476f-999e-ee008881723c.yml
  content/taxonomy_term/7888c194-dcee-4cbb-866d-b59f44113396.yml
  content/taxonomy_term/87edc9eb-344d-4dde-8b8f-e78dff007eba.yml
  content/taxonomy_term/8ad381b4-5b30-4afe-83f9-32ab80d009f6.yml
  content/taxonomy_term/8dfbbc5f-2bfb-46ae-b00f-1245a6ad6843.yml
  content/taxonomy_term/9856eb23-d550-4103-a078-18da2d414be9.yml
  content/taxonomy_term/a464983f-65d2-4396-8db5-b64dc680818d.yml
  content/taxonomy_term/a5ae8281-11c2-4f06-abc8-6b01d60b20a8.yml
  content/taxonomy_term/af0d33be-0896-4991-82f7-bdab3ef9ca57.yml
  content/taxonomy_term/b0efc5ea-fbf1-482d-9294-c298d76e2800.yml
  content/taxonomy_term/b6d9a5f0-96f1-4b79-8604-cdefd0bb424c.yml
  content/taxonomy_term/d6389b12-e0b7-413a-a464-e9c2939b55aa.yml
  content/taxonomy_term/dc6ac0c7-4e4d-4cd1-966f-d03ec01d32f2.yml
  content/taxonomy_term/de0aa1c0-d860-4afb-b5e3-729542c9b773.yml
  content/taxonomy_term/e27eaa81-11c6-4381-88df-0f567d5e9bde.yml
  content/taxonomy_term/e30a5335-3d70-4064-b143-6ab375e0267a.yml
  content/taxonomy_term/ee2dfea1-f772-46d9-8746-5958c0e0d94e.yml
  content/taxonomy_term/ef8ea5fd-ef65-4565-8417-7331b048d464.yml
  content/taxonomy_term/f1ea54b3-3c20-4cf4-8c4c-8fb741780bec.yml
  tests/codeception/acceptance/Content/EventsCest.php
Labels: patch, size/s

#738 11.0.4
  CHANGELOG.md
  stanford_profile.info.yml
  tests/codeception/acceptance/Content/SearchBlockCest.php
  tests/codeception/acceptance/SystemSiteConfigCest.php
  tests/codeception/functional/Contrib/ExtLinkCest.php
  tests/codeception/functional/Navigation/NavigationDropDownsCest.php
Labels: patch, size/xs

#739 Adjust event card test
  CHANGELOG.md
  config/sync/smart_date.smart_date_format.day.yml
  config/sync/smart_date.smart_date_format.short_month.yml
  stanford_profile.info.yml
  tests/codeception/acceptance/Content/EventsCest.php
  tests/codeception/acceptance/SystemCest.php
Labels: patch, size/xs

#740 11.0.7
  CHANGELOG.md
  stanford_profile.info.yml
Labels: patch, size/xs

#741 D8CORE-7066 Adjust site contact fields
  config/sync/core.entity_form_display.config_pages.stanford_basic_site_settings.default.yml
  config/sync/field.field.config_pages.stanford_basic_site_settings.su_google_analytics.yml
  config/sync/field.field.config_pages.stanford_basic_site_settings.su_site_a11y_contact.yml
  config/sync/field.field.config_pages.stanford_basic_site_settings.su_site_dropdowns.yml
  config/sync/field.field.config_pages.stanford_basic_site_settings.su_site_owner_contact.yml
  config/sync/field.field.config_pages.stanford_basic_site_settings.su_site_tech_contact.yml
  config/sync/field.storage.config_pages.su_site_email.yml
  src/EventSubscriber/EventSubscriber.php
  tests/codeception/acceptance/Content/SearchBlockCest.php
  tests/codeception/acceptance/SystemSiteConfigCest.php
  tests/codeception/functional/Contrib/ExtLinkCest.php
  tests/codeception/functional/Navigation/NavigationDropDownsCest.php
Labels: size/xs

#742 11.0.8
  CHANGELOG.md
  stanford_profile.info.yml
Labels: patch, size/xs
