Repository SU-SWS/stanford_profile, pull requests merged in 2024-03, with the labels that each got.

#773 D8CORE-6983: added test for stacking site_embedder role
  tests/codeception/acceptance/Users/RolesCest.php
Labels: size/xs

#774 D8CORE-7333 Change paragraph behaviors for teaser and lists
  config/sync/paragraphs.paragraphs_type.stanford_entity.yml
  config/sync/paragraphs.paragraphs_type.stanford_lists.yml
Labels: size/xs

#775 Fix News metadata test
  tests/codeception/acceptance/Content/NewsCest.php
Labels: size/xs

#776 11.3.0
  CHANGELOG.md
  composer.json
  stanford_profile.info.yml
Labels: size/xs, minor

#777 11.3.1
  CHANGELOG.md
  stanford_profile.info.yml
  tests/codeception/functional/Paragraphs/WYSIWYGCest.php
Labels: patch, size/xs

#778 11.3.2
  CHANGELOG.md
  stanford_profile.info.yml
Labels: patch, size/xs

#779 11.3.3
  CHANGELOG.md
  stanford_profile.info.yml
Labels: patch

#781 11.3.4
  CHANGELOG.md
  stanford_profile.info.yml
Labels: patch, size/xs

#782 11.3.5
  CHANGELOG.md
  stanford_profile.info.yml
Labels: patch

#783 D8CORE-000 Update Past Event List
  config/sync/views.view.stanford_events.yml
  config/sync/views.view.stanford_publications.yml
Labels: size/xs

#784 11.3.6
  CHANGELOG.md
  stanford_profile.info.yml
Labels: patch, size/xs
