Repository SU-SWS/stanford_profile, pull requests merged in 2024-09, with the labels that each got.

#799 D8CORE-7424 Added various HTML attributes to the WSYIWYG allowed list
  config/sync/editor.editor.stanford_html.yml
  config/sync/editor.editor.stanford_minimal_html.yml
  config/sync/filter.format.stanford_html.yml
  config/sync/filter.format.stanford_minimal_html.yml
Labels: size/xs

#809 11.4.0
  CHANGELOG.md
  composer.json
  stanford_profile.info.yml
Labels: size/xs, minor

#807 D8Core-7476: Site Type
  config/sync/core.entity_form_display.config_pages.stanford_basic_site_settings.default.yml
  config/sync/core.entity_view_display.config_pages.stanford_basic_site_settings.default.yml
  config/sync/field.field.config_pages.stanford_basic_site_settings.su_site_type.yml
  config/sync/field.storage.config_pages.su_site_type.yml
Labels: size/s

#810 11.4.1
  CHANGELOG.md
  stanford_profile.info.yml
Labels: patch, size/xs

#811 Adjust codeception list test
  tests/codeception/acceptance/Paragraphs/ListsCest.php
Labels: size/xs

#812 11.4.2
  CHANGELOG.md
  stanford_profile.info.yml
Labels: patch, size/xs

#817 11.4.3
  CHANGELOG.md
  config/sync/core.entity_view_display.paragraph.stanford_page_title_banner.variant_1.yml
  stanford_profile.info.yml
Labels: patch, size/xs

#818 11.4.4
  CHANGELOG.md
  composer.json
  stanford_profile.info.yml
Labels: patch, size/xs

#819 D8Core-7515: Additional Site Type Options
  config/sync/field.field.config_pages.stanford_basic_site_settings.su_site_type.yml
  config/sync/field.storage.config_pages.su_site_type.yml
Labels: size/xs
