Repository SU-SWS/stanford_profile, pull requests merged in 2024-11, with the labels that each got.

#827 Added FAQ Accordion paragraph type
  .gitignore
  config/sync/core.entity_form_display.paragraph.stanford_faq.default.yml
  config/sync/core.entity_view_display.paragraph.stanford_faq.default.yml
  config/sync/field.field.node.stanford_event.su_event_components.yml
  config/sync/field.field.node.stanford_event_series.su_event_series_components.yml
  config/sync/field.field.node.stanford_news.su_news_components.yml
  config/sync/field.field.node.stanford_opportunity.su_opp_components.yml
  config/sync/field.field.node.stanford_page.su_page_components.yml
  config/sync/field.field.node.stanford_person.su_person_components.yml
  config/sync/field.field.node.stanford_publication.su_publication_components.yml
  config/sync/field.field.paragraph.stanford_faq.su_faq_description.yml
  config/sync/field.field.paragraph.stanford_faq.su_faq_headline.yml
  config/sync/field.field.paragraph.stanford_faq.su_faq_questions.yml
  config/sync/field.storage.paragraph.su_faq_description.yml
  config/sync/field.storage.paragraph.su_faq_headline.yml
  config/sync/field.storage.paragraph.su_faq_questions.yml
  config/sync/graphql_compose.settings.yml
  config/sync/paragraphs.paragraphs_type.stanford_faq.yml
  tests/codeception/functional/Paragraphs/AccordionCest.php
  themes/stanford_basic/.yarnrc.yml
  themes/stanford_basic/dist/css/base.css
  themes/stanford_basic/dist/css/components.css
  themes/stanford_basic/dist/css/user_login.css
  themes/stanford_basic/dist/js/base.js
  themes/stanford_basic/dist/js/behaviors.js
  themes/stanford_basic/package.json
  themes/stanford_basic/src/js/stanford_basic.behavior.js
  themes/stanford_basic/src/scss/components/accordion-list/_accrdion-list.scss
  themes/stanford_basic/src/scss/components/accordion-list/index.scss
  themes/stanford_basic/src/scss/components/all/_vertical-spacing.scss
  themes/stanford_basic/src/scss/components/index.scss
  themes/stanford_basic/webpack.config.js
  themes/stanford_basic/yarn.lock
Labels: size/xl

#820 D8CORE-7558: added the global footer in dark with no logo
  tests/codeception/acceptance/SubThemeCest.php
  themes/minimally_branded_subtheme/dist/css/minimally_branded_subtheme.css
  themes/minimally_branded_subtheme/src/scss/components/global-footer/_global-footer.scss
  themes/minimally_branded_subtheme/src/scss/components/global-footer/index.scss
  themes/minimally_branded_subtheme/src/scss/components/index.scss
  themes/minimally_branded_subtheme/templates/components/global-footer/global-footer.html.twig
Labels: size/xs

#828 D8CORE-7578 Adjust person display for lists and improve resolution
  config/sync/core.entity_view_display.node.stanford_person.default.yml
  config/sync/core.entity_view_display.node.stanford_person.stanford_h3_card_plain.yml
  config/sync/core.entity_view_mode.node.stanford_h3_card_plain.yml
  config/sync/views.view.stanford_person.yml
Labels: size/s

#830 11.5.0
  CHANGELOG.md
  config/sync/field.field.paragraph.stanford_faq.su_faq_description.yml
  content/config_pages/5a3a16f1-adb6-4946-b957-49c5bb13ef8f.yml
  content/node/6df8090b-5dca-4386-9d72-d86e0156c0a9.yml
  src/EventSubscriber/EventSubscriber.php
  stanford_profile.info.yml
  tests/codeception/acceptance/Content/EventsCest.php
  tests/codeception/acceptance/SuperFooter/SuperFooterCest.php
  tests/codeception/functional/Contrib/ExtLinkCest.php
  themes/stanford_basic/templates/html.html.twig
Labels: size/xs, minor
