Repository SU-SWS/stanford_profile, pull requests merged in 2024-10, with the labels that each got.

#816 D8CORE-7517 | update event subtitle heading
  config/sync/views.view.stanford_events.yml
Labels: size/xs

#822 D8CORE-7564: removed decanter link and replaced with identity guide
  config/sync/field.field.config_pages.lockup_settings.su_intro.yml
  themes/stanford_basic/theme-settings.php
Labels: size/xs

#821 Remove edit links in views
  config/sync/views.view.stanford_basic_pages.yml
  config/sync/views.view.stanford_courses.yml
  config/sync/views.view.stanford_event_series.yml
  config/sync/views.view.stanford_events.yml
  config/sync/views.view.stanford_news.yml
  config/sync/views.view.stanford_person.yml
  config/sync/views.view.stanford_publications.yml
Labels: size/m

#823 11.4.5
  CHANGELOG.md
  config/sync/core.entity_form_display.config_pages.stanford_basic_site_settings.default.yml
  config/sync/core.entity_view_display.config_pages.stanford_basic_site_settings.default.yml
  config/sync/field.field.config_pages.stanford_basic_site_settings.su_site_created.yml
  config/sync/field.storage.config_pages.su_site_created.yml
  src/Plugin/InstallTask/SiteSettings.php
  stanford_profile.info.yml
  tests/src/Kernel/Plugin/InstallTask/SiteSettingsTest.php
Labels: patch, size/s

#824 Fix acceptance tests after contrib updates
  config/sync/views.view.content.yml
  config/sync/views.view.files.yml
  tests/codeception/acceptance/Contrib/ViewsBulkEditCest.php
  tests/codeception/acceptance/Media/MediaCest.php
  tests/codeception/functional/Users/RolesCest.php
Labels: size/xs

#826 Added modal colorbox image display choices in the wysiwyg
  config/sync/core.entity_view_display.media.image.large_modal.yml
  config/sync/core.entity_view_display.media.image.medium_modal.yml
  config/sync/core.entity_view_display.media.image.small_modal.yml
  config/sync/core.entity_view_mode.media.large_modal.yml
  config/sync/core.entity_view_mode.media.medium_modal.yml
  config/sync/core.entity_view_mode.media.small_modal.yml
  config/sync/filter.format.stanford_html.yml
  tests/codeception/functional/Paragraphs/WYSIWYGCest.php
Labels: size/s
