Repository SU-SWS/stanford_profile, pull requests merged in 2024-02, with the labels that each got.

#759 Update GH Actions checkout
  .github/workflows/label.yml
  .github/workflows/tests.yml
  config/sync/block.block.stanford_basic_pagetitle.yml
Labels: size/xs

#760 D8CORE-7255 exclude lazy load oembed links from external links
  config/sync/extlink.settings.yml
  themes/stanford_basic/templates/contrib/oembed-lazyload-placeholder.html.twig
Labels: size/xs

#761 D8CORE-7125 Use field_label module to choose which heading element for field labels
  composer.json
  config/sync/core.entity_view_display.node.stanford_person.default.yml
  config/sync/core.extension.yml
  config/sync/field_label.settings.yml
  themes/stanford_basic/templates/block/block--layout-builder.html.twig
  themes/stanford_basic/templates/core/field.html.twig
Labels: size/xs

#764 11.2.0
  CHANGELOG.md
  composer.json
  stanford_profile.info.yml
Labels: size/xs, minor

#766 11.2.1
  CHANGELOG.md
  stanford_profile.info.yml
Labels: patch, size/xs

#770 11.2.1
  CHANGELOG.md
  stanford_profile.info.yml
  themes/stanford_basic/algolia-search/dist/islands/algolia-search.island.js
  themes/stanford_basic/algolia-search/src/algolia-search.island.tsx
  themes/stanford_basic/algolia-search/src/hits/default-hit.tsx
Labels: patch, size/xs

#754 D8CORE-7207 Add Page Title Banner Paragraph
  config/sync/core.entity_form_display.node.stanford_page.default.yml
  config/sync/core.entity_form_display.paragraph.stanford_page_title_banner.default.yml
  config/sync/core.entity_view_display.paragraph.stanford_page_title_banner.default.yml
  config/sync/ds.field.page_title.yml
  config/sync/field.field.node.stanford_page.su_page_banner.yml
  config/sync/field.field.paragraph.stanford_page_title_banner.su_title_banner_image.yml
  config/sync/field.storage.paragraph.su_title_banner_image.yml
  config/sync/filter.format.administrative_html.yml
  config/sync/filter.format.plain_text.yml
  config/sync/filter.format.stanford_html.yml
  config/sync/filter.format.stanford_minimal_html.yml
  config/sync/graphql_compose.settings.yml
  config/sync/jsonapi_extras.jsonapi_resource_config.paragraph--stanford_page_title_banner.yml
  config/sync/paragraphs.paragraphs_type.stanford_banner.yml
  config/sync/paragraphs.paragraphs_type.stanford_page_title_banner.yml
  tests/codeception/acceptance/Paragraphs/PageTitleBannerCest.php
  themes/stanford_basic/dist/css/components.css
  themes/stanford_basic/src/scss/components/hero/_hero.scss
Labels: size/s

#771 Remove paragraph row configs
  config/sync/core.entity_form_display.paragraph_row.su_pub_rows.default.yml
  config/sync/core.entity_view_display.paragraph_row.node_stanford_page_row.default.yml
  config/sync/core.entity_view_display.paragraph_row.su_pub_rows.default.yml
  config/sync/field.field.paragraph_row.node_stanford_page_row.su_page_components.yml
  config/sync/field.field.paragraph_row.su_pub_rows.su_pubs_components.yml
  config/sync/field.storage.paragraph_row.su_page_components.yml
  config/sync/field.storage.paragraph_row.su_pubs_components.yml
  config/sync/paragraphs.paragraphs_type.stanford_banner.yml
  config/sync/paragraphs.paragraphs_type.stanford_card.yml
  config/sync/paragraphs.paragraphs_type.stanford_page_title_banner.yml
  config/sync/react_paragraphs.paragraphs_row_type.node_stanford_page_row.yml
  config/sync/react_paragraphs.paragraphs_row_type.su_pub_rows.yml
  stanford_profile.install
Labels: size/s
