Repository SU-SWS/stanford_profile, pull requests merged in 2025-02, with the labels that each got.

#868 D8CORE-7806: Gave site owners permissions to assign Reviewer role.
  config/sync/user.role.site_manager.yml
Labels: size/xs

#869 11.5.3
  CHANGELOG.md
  stanford_profile.info.yml
Labels: patch, size/xs

#870 D8CORE-7813: fixed the text color in the more publications button - Minimal branding subtheme.
  themes/minimally_branded_subtheme/dist/css/minimally_branded_subtheme.css
  themes/minimally_branded_subtheme/src/scss/theme/_link.scss
Labels: size/xs

#833 D8CORE-7663: reorganized the opportunity node page
  config/sync/core.entity_view_display.node.stanford_opportunity.default.yml
  config/sync/field.field.node.stanford_opportunity.su_opp_contact_email.yml
Labels: size/s

#871 D8CORE-7737 D8CORE-7738 D8CORE-7824 Install state changes
  config/sync/core.entity_form_display.config_pages.stanford_basic_site_settings.default.yml
  config/sync/core.entity_view_display.config_pages.stanford_basic_site_settings.default.yml
  config/sync/field.field.config_pages.stanford_basic_site_settings.su_site_sunetid.yml
  config/sync/field.storage.config_pages.su_site_sunetid.yml
  config/sync/field_validation.rule_set.config_pages_stanford_basic_site_settings.yml
  content/config_pages/0d7e973e-6b97-4243-a373-d486a581eb84.yml
  content/node/72f0069b-f1ec-4122-af73-6aa841faea90.yml
  src/Plugin/InstallTask/SiteSettings.php
  tests/codeception/acceptance/AuthenticatedPermissionsCest.php
  tests/codeception/acceptance/Content/EventsCest.php
  tests/codeception/acceptance/GlobalMessage/GlobalMessageCest.php
  tests/codeception/acceptance/HomePageCest.php
  tests/codeception/acceptance/LocalFooter/LocalFooterCest.php
  tests/codeception/acceptance/LocalFooter/LocalFooterLockupCest.php
  tests/codeception/acceptance/SubThemeCest.php
  tests/codeception/acceptance/SuperFooter/SuperFooterCest.php
  tests/codeception/acceptance/SystemSiteConfigCest.php
  tests/codeception/acceptance/Users/IntranetCest.php
Labels: size/s

#873 Implement shield on dev and stage
  composer.json
  config/sync/config_split.config_split.dev.yml
  config/sync/config_split.config_split.local.yml
  config/sync/config_split.config_split.stage.yml
  tests/codeception/acceptance/Users/RolesCest.php
Labels: size/xs

#875 D8CORE-7885: Change Character Limit for Accordion
  config/sync/core.entity_form_display.paragraph.stanford_accordion.default.yml
Labels: size/xs

#874 D8CORE-7723: Allow unpublishing of taxonomy terms
  config/sync/core.entity_form_display.taxonomy_term.basic_page_types.default.yml
  config/sync/core.entity_form_display.taxonomy_term.stanford_event_types.default.yml
  config/sync/core.entity_form_display.taxonomy_term.stanford_news_topics.default.yml
  config/sync/core.entity_form_display.taxonomy_term.stanford_person_types.default.yml
  config/sync/core.entity_form_display.taxonomy_term.stanford_publication_topics.default.yml
Labels: size/xs
