Repository SU-SWS/stanford_profile, pull requests merged in 2025-06, with the labels that each got.

#940 Require headline in stat card
  config/sync/field.field.paragraph.stanford_stat_card.su_stat_headline.yml
  tests/codeception/acceptance/Content/BasicPageCest.php
Labels: size/xs

#948 Fixed utility nav on decoupled menu
  themes/stanford_basic/decoupled-menu/dist/islands/main-menu.island.umd.js
  themes/stanford_basic/decoupled-menu/package.json
  themes/stanford_basic/decoupled-menu/src/main-menu.island.tsx
  themes/stanford_basic/decoupled-menu/yarn.lock
  themes/stanford_basic/package.json
  themes/stanford_basic/yarn.lock
Labels: size/l

#935 D8CORE-7987: Copy the utility links and buttons for the mobile display
  themes/stanford_basic/decoupled-menu/dist/islands/main-menu.island.umd.js
  themes/stanford_basic/decoupled-menu/package.json
  themes/stanford_basic/decoupled-menu/src/main-menu.island.tsx
  themes/stanford_basic/decoupled-menu/yarn.lock
  themes/stanford_basic/dist/css/components.css
  themes/stanford_basic/dist/js/behaviors.js
  themes/stanford_basic/package.json
  themes/stanford_basic/src/js/stanford_basic.behavior.js
  themes/stanford_basic/src/scss/components/masthead/_wrapper.scss
  themes/stanford_basic/yarn.lock
Labels: size/s, size/l

#943 D8CORE-8045: Adding spacing to header bottom when there is no navigation menu.
  themes/stanford_basic/dist/css/components.css
  themes/stanford_basic/dist/js/behaviors.js
  themes/stanford_basic/src/js/stanford_basic.behavior.js
  themes/stanford_basic/src/scss/components/masthead/_wrapper.scss
Labels: size/xs

#950 Adjust opportunity filters to use radio buttons
  config/sync/views.view.stanford_opportunities_filtered.yml
Labels: size/xs

#953 11.8.0
  CHANGELOG.md
  composer.json
  stanford_profile.info.yml
Labels: size/xs, minor

#956 UE-536: adjusting layout to be in only 2 cols
  config/sync/core.entity_view_display.node.stanford_opportunity.default.yml
  themes/stanford_basic/stanford_basic.theme
Labels: size/xs

#962 11.8.3
  CHANGELOG.md
  stanford_profile.info.yml
Labels: patch, size/xs
