Repository SU-SWS/stanford_profile, pull requests merged in 2025-04, with the labels that each got.

#899 Ensure failed codeception tests flag as failures
  .github/workflows/tests.yml
Labels: size/xs

#898 DCORE-7898 - Opportunities node config take2
  config/sync/core.entity_form_display.node.stanford_opportunity.default.yml
  config/sync/core.entity_view_display.node.stanford_opportunity.default.yml
Labels: size/s

#896 D8CORE-7897 Edit Form Cleanup
  config/sync/core.base_field_override.node.stanford_opportunity.status.yml
  config/sync/core.entity_form_display.node.stanford_opportunity.default.yml
  config/sync/field.field.node.stanford_opportunity.body.yml
  config/sync/field.field.node.stanford_opportunity.su_opp_application_deadline.yml
  config/sync/field.field.node.stanford_opportunity.su_opp_card_footer.yml
  config/sync/field.field.node.stanford_opportunity.su_opp_course_code.yml
  config/sync/field.field.node.stanford_opportunity.su_opp_cta_url.yml
  config/sync/field.field.node.stanford_opportunity.su_opp_eligibility.yml
  config/sync/field.field.node.stanford_opportunity.su_opp_icon.yml
  config/sync/field.field.node.stanford_opportunity.su_opp_image.yml
  config/sync/field.field.node.stanford_opportunity.su_opp_learn_more.yml
  config/sync/field.field.node.stanford_opportunity.su_opp_prerequisites.yml
  config/sync/field.field.node.stanford_opportunity.su_opp_source.yml
  config/sync/field.field.node.stanford_opportunity.su_opp_summary.yml
  config/sync/field.field.node.stanford_opportunity.su_opp_tags.yml
  config/sync/field.field.node.stanford_opportunity.su_opp_type.yml
  config/sync/field.field.node.stanford_opportunity.su_opp_units.yml
  config/sync/node.type.stanford_opportunity.yml
Labels: size/s

#906 D8CORE-7945: units added to the opportunities node page
  config/sync/core.entity_view_display.node.stanford_opportunity.default.yml
Labels: size/xs

#901 D8CORE-7939: Metatags for Opportunities
  config/sync/metatag.metatag_defaults.node__stanford_opportunity.yml
Labels: size/xs

#908 D8CORE-7951: updated the card opp. list
  config/sync/core.entity_view_display.node.stanford_opportunity.stanford_h3_card.yml
  config/sync/core.entity_view_display.node.stanford_opportunity.teaser.yml
Labels: size/s

#900 D8CORE-7924 Add header utility links to site settings
  config/sync/block.block.minimally_branded_subtheme_header_links.yml
  config/sync/block.block.stanford_basic_header_links.yml
  config/sync/core.entity_form_display.config_pages.stanford_basic_site_settings.default.yml
  config/sync/core.entity_view_display.config_pages.stanford_basic_site_settings.default.yml
  config/sync/core.entity_view_display.config_pages.stanford_basic_site_settings.site_settings_header.yml
  config/sync/core.entity_view_mode.config_pages.site_settings_header.yml
  config/sync/field.field.config_pages.stanford_basic_site_settings.su_site_header_button.yml
  config/sync/field.field.config_pages.stanford_basic_site_settings.su_site_header_links.yml
  config/sync/field.storage.config_pages.su_site_header_button.yml
  config/sync/field.storage.config_pages.su_site_header_links.yml
  config/sync/graphql_compose.settings.yml
  stanford_profile.post_update.php
  tests/codeception/acceptance/SystemSiteConfigCest.php
  tests/codeception/functional/Navigation/NavigationDropDownsCest.php
  themes/stanford_basic/dist/css/components.css
  themes/stanford_basic/dist/js/behaviors.js
  themes/stanford_basic/package.json
  themes/stanford_basic/src/scss/components/masthead/_wrapper.scss
  themes/stanford_basic/templates/page.html.twig
  themes/stanford_basic/yarn.lock
Labels: size/m

#909 D8CORE-7936: Fixes to the node per design request.
  config/sync/core.entity_view_display.node.stanford_opportunity.default.yml
Labels: size/xs

#913 D8CORE-8006: Removed link on Opportunity card image
  config/sync/core.entity_view_display.node.stanford_opportunity.stanford_card.yml
  config/sync/core.entity_view_display.node.stanford_opportunity.stanford_h3_card.yml
Labels: size/xs

#910 D8CORE-7957 - Default Content: Term Removal
  config/sync/block.block.minimally_branded_subtheme_header_links.yml
  config/sync/block.block.stanford_basic_header_links.yml
  config/sync/core.entity_form_display.config_pages.stanford_basic_site_settings.default.yml
  config/sync/core.entity_view_display.config_pages.stanford_basic_site_settings.default.yml
  config/sync/core.entity_view_display.config_pages.stanford_basic_site_settings.site_settings_header.yml
  config/sync/core.entity_view_display.node.stanford_event.search_indexing.yml
  config/sync/core.entity_view_display.node.stanford_news.search_indexing.yml
  config/sync/core.entity_view_display.node.stanford_person.search_indexing.yml
  config/sync/core.entity_view_display.node.stanford_policy.search_indexing.yml
  config/sync/core.entity_view_display.node.stanford_publication.search_indexing.yml
  config/sync/core.entity_view_mode.config_pages.site_settings_header.yml
  config/sync/field.field.config_pages.stanford_basic_site_settings.su_site_header_button.yml
  config/sync/field.field.config_pages.stanford_basic_site_settings.su_site_header_links.yml
  config/sync/field.storage.config_pages.su_site_header_button.yml
  config/sync/field.storage.config_pages.su_site_header_links.yml
  config/sync/graphql_compose.settings.yml
  content/taxonomy_term/254eea9a-320a-400a-b12c-a7bc582d9f61.yml
  content/taxonomy_term/42d15ff2-9a03-418e-8298-704909f22779.yml
  content/taxonomy_term/59456731-36df-4d80-999d-eea34175f622.yml
  content/taxonomy_term/640473e4-2dcf-494d-b583-febff0352d3b.yml
  content/taxonomy_term/66513756-0056-456e-b0b2-7d3438e7ac65.yml
  content/taxonomy_term/67d3e82b-5d77-49ee-8821-26e278d86f59.yml
  content/taxonomy_term/6a4ed963-bdb8-4ad5-9162-d0e6c319bc19.yml
  content/taxonomy_term/94a3e0f8-b9a8-47f9-8d47-5b7e02e5b07f.yml
  content/taxonomy_term/9d9d1d6b-cfe0-471c-a621-7b0161eafc8a.yml
  content/taxonomy_term/beb0218b-a76c-4f72-a485-b00271d380d5.yml
  content/taxonomy_term/d01c2178-65fc-48eb-a427-100850e99649.yml
  content/taxonomy_term/df98b493-6c5a-41e4-b21a-6506045b4ef0.yml
  content/taxonomy_term/e8c58911-9775-4393-83db-a3beddd58e08.yml
  content/taxonomy_term/ecfa5c86-dbd0-4007-95b8-02b6ee574a2c.yml
  content/taxonomy_term/eda262e0-4fba-452d-bb47-9ae84b576b8b.yml
  content/taxonomy_term/ee1e20b8-ffc3-490f-8975-9fe281cad65c.yml
  content/taxonomy_term/fb6a03cb-6d0d-4a08-8e89-cb518cf4e9c5.yml
  stanford_profile.install
  stanford_profile.post_update.php
  tests/codeception/acceptance/SystemSiteConfigCest.php
  tests/codeception/functional/Navigation/NavigationDropDownsCest.php
  themes/stanford_basic/dist/css/components.css
  themes/stanford_basic/dist/js/behaviors.js
  themes/stanford_basic/package.json
  themes/stanford_basic/src/scss/components/masthead/_wrapper.scss
  themes/stanford_basic/templates/page.html.twig
  themes/stanford_basic/yarn.lock
Labels: size/l

#912 D8CORE-7945 units remove comma
  config/sync/core.entity_view_display.node.stanford_opportunity.default.yml
  themes/stanford_basic/templates/field/cshs-term-group--su-opp-tags.html.twig
  themes/stanford_basic/templates/field/field--su-opp-type.html.twig
Labels: size/xs

#914 D8CORE-7998: View More
  config/sync/views.view.stanford_opportunities_filtered.yml
Labels: size/xs

#915 D8CORE-8015 : Opportunities content management view
  config/sync/views.view.manage_content.yml
Labels: size/l

#916 D8CORE-7997: Updated edit form for Site Header Options
  config/sync/core.entity_form_display.config_pages.stanford_basic_site_settings.default.yml
  config/sync/core.entity_view_display.config_pages.stanford_basic_site_settings.site_settings_header.yml
  tests/codeception/acceptance/SystemSiteConfigCest.php
  tests/codeception/functional/Navigation/NavigationDropDownsCest.php
Labels: size/xs

#917 D8CORE-000: filtered list layout
  config/sync/core.entity_view_display.node.stanford_opportunity.default.yml
Labels: size/xs

#911 D8CORE-7927: Utility navigation styles
  themes/stanford_basic/dist/css/components.css
  themes/stanford_basic/src/scss/components/masthead/_wrapper.scss
Labels: size/xs
