Repository SU-SWS/stanford_profile, pull requests merged in 2025-08, with the labels that each got.

#971 D8CORE-8195: Added external source field and functionality to policy content type
  config/sync/core.entity_form_display.node.stanford_policy.default.yml
  config/sync/core.entity_view_display.node.stanford_policy.default.yml
  config/sync/core.entity_view_display.node.stanford_policy.printable.yml
  config/sync/core.entity_view_display.node.stanford_policy.search_indexing.yml
  config/sync/core.entity_view_display.node.stanford_policy.stanford_card.yml
  config/sync/core.entity_view_display.node.stanford_policy.stanford_h3_card.yml
  config/sync/core.entity_view_display.node.stanford_policy.teaser.yml
  config/sync/field.field.node.stanford_policy.su_policy_source.yml
  config/sync/field.storage.node.su_policy_source.yml
  config/sync/node.type.stanford_policy.yml
  config/sync/rabbit_hole.behavior_settings.node_type_stanford_policy.yml
  tests/codeception/acceptance/Content/PolicyCest.php
Labels: size/s

#967 D8CORE-8028: Added ext link icons to Utility nav
  config/sync/extlink.settings.yml
  themes/stanford_basic/dist/css/components.css
  themes/stanford_basic/src/scss/components/masthead/_wrapper.scss
Labels: size/xs

#972 D8Core-8174: RSS Feeds for Events
  config/sync/views.view.stanford_events.yml
Labels: size/m

#970 D8CORE-7585: Updating design for federated search
  themes/stanford_basic/algolia-search/dist/islands/algolia-search.island.js
  themes/stanford_basic/algolia-search/package.json
  themes/stanford_basic/algolia-search/src/algolia-search.island.tsx
  themes/stanford_basic/algolia-search/src/components/chips-button.tsx
  themes/stanford_basic/algolia-search/src/components/chips-container.tsx
  themes/stanford_basic/algolia-search/src/components/chips-item.tsx
  themes/stanford_basic/algolia-search/src/components/custom-chips.tsx
  themes/stanford_basic/algolia-search/src/federated-search-facets.tsx
  themes/stanford_basic/algolia-search/src/hits/default-hit.tsx
  themes/stanford_basic/algolia-search/src/search-box.tsx
  themes/stanford_basic/algolia-search/src/styled-components.tsx
  themes/stanford_basic/algolia-search/yarn.lock
  themes/stanford_basic/dist/css/search-page.css
  themes/stanford_basic/src/scss/pages/search/_search-page.scss
  themes/stanford_basic/stanford_basic.libraries.yml
Labels: size/xs, size/m, size/s, size/l

#976 Update stanford fields module
  composer.json
Labels: size/xs

#977 D8CORE-8276: Design edits to the Federated Search results
  themes/stanford_basic/algolia-search/dist/islands/algolia-search.island.js
  themes/stanford_basic/algolia-search/src/federated-search-facets.tsx
  themes/stanford_basic/algolia-search/src/styled-components.tsx
  themes/stanford_basic/dist/css/search-page.css
  themes/stanford_basic/src/scss/pages/search/_search-page.scss
Labels: size/s

#980 Remove bulk publish and unpublish options from manage content pages
  config/sync/views.view.content.yml
  config/sync/views.view.manage_content.yml
Labels: size/xs

#982 D8CORE-8279: A11y changes for federated search
  themes/stanford_basic/algolia-search/dist/islands/algolia-search.island.js
  themes/stanford_basic/algolia-search/src/algolia-search.island.tsx
  themes/stanford_basic/algolia-search/src/search-box.tsx
  themes/stanford_basic/algolia-search/src/styled-components.tsx
Labels: size/xs

#983 12.0.1
  CHANGELOG.md
  stanford_profile.info.yml
Labels: patch, size/xs

#986 12.0.2
  CHANGELOG.md
  stanford_profile.info.yml
Labels: patch, size/xs
