Repository SU-SWS/stanford_profile, pull requests merged in 2025-03, with the labels that each got.

#877 Adjust test for taxonomy term publish field
  tests/codeception/acceptance/Content/BasicPageCest.php
  tests/codeception/acceptance/Content/EventsCest.php
  tests/codeception/acceptance/Content/NewsCest.php
  tests/codeception/acceptance/Content/PersonCest.php
  tests/codeception/acceptance/Content/PublicationsCest.php
Labels: size/xs

#864 D8CORE-7292 - Updated the help pages.
  .github/workflows/tests.yml
  src/Plugin/HelpSection/ProfileConnectSection.php
  src/Plugin/HelpSection/ProfileHelpMaintainingSection.php
  src/Plugin/HelpSection/ProfileHelpSection.php
  src/Plugin/HelpSection/ProfileResourceSection.php
  tests/src/Unit/Plugin/HelpSection/ProfileHelpSectionTest.php
  tests/src/Unit/Plugin/HelpSection/ProfileMaintainingSectionTest.php
  tests/src/Unit/Plugin/HelpSection/ProfileResourceSectionTest.php
  themes/stanford_profile_admin_theme/templates/misc/help/help-section.html.twig
Labels: size/s

#881 11.6.0
  CHANGELOG.md
  stanford_profile.info.yml
  themes/stanford_basic/src/js/stanford_basic.behavior.js
Labels: size/xs, minor

#882 Improve embeddable media test
  tests/codeception/acceptance/Media/MediaCest.php
  tests/codeception/functional/Navigation/NavigationDropDownsCest.php
Labels: size/xs

#884 11.6.1
  CHANGELOG.md
  stanford_profile.info.yml
Labels: patch, size/xs

#885 fixup acceptance tests
  tests/codeception/acceptance/Media/MediaCest.php
  tests/codeception/functional/Navigation/NavigationDropDownsCest.php
Labels: size/xs

#889 11.6.2
  CHANGELOG.md
  stanford_profile.info.yml
  themes/stanford_basic/stanford_basic.theme
Labels: patch, size/xs

#886 D8CORE-7506: Additional Fields
  config/sync/core.entity_form_display.node.stanford_opportunity.default.yml
  config/sync/core.entity_view_display.node.stanford_opportunity.default.yml
  config/sync/core.entity_view_display.node.stanford_opportunity.full.yml
  config/sync/core.entity_view_display.node.stanford_opportunity.search_indexing.yml
  config/sync/core.entity_view_display.node.stanford_opportunity.stanford_card.yml
  config/sync/core.entity_view_display.node.stanford_opportunity.stanford_h3_card.yml
  config/sync/core.entity_view_display.node.stanford_opportunity.teaser.yml
  config/sync/field.field.node.stanford_opportunity.su_opp_card_footer.yml
  config/sync/field.field.node.stanford_opportunity.su_opp_icon.yml
  config/sync/field.field.node.stanford_opportunity.su_opp_units.yml
  config/sync/field.storage.node.su_opp_card_footer.yml
  config/sync/field.storage.node.su_opp_icon.yml
  config/sync/field.storage.node.su_opp_units.yml
Labels: patch, size/s

#888 D8CORE-7662 new layout name
  CHANGELOG.md
  config/sync/paragraphs.paragraphs_type.stanford_layout.yml
  stanford_profile.info.yml
  tests/codeception/acceptance/Media/MediaCest.php
  tests/codeception/functional/Navigation/NavigationDropDownsCest.php
Labels: patch, size/xs

#893 D8CORE-7734: Remove requirement for contact email
  config/sync/field.field.node.stanford_opportunity.su_opp_contact_email.yml
Labels: size/xs

#892 D8CORE-7506: Update to Units
  config/sync/core.entity_form_display.node.stanford_opportunity.default.yml
  config/sync/core.entity_form_display.taxonomy_term.opportunity_units.default.yml
  config/sync/core.entity_view_display.node.stanford_opportunity.default.yml
  config/sync/field.field.node.stanford_opportunity.su_opp_units.yml
  config/sync/field.storage.node.su_opp_units.yml
  config/sync/rabbit_hole.behavior_settings.taxonomy_vocabulary_opportunity_units.yml
  config/sync/taxonomy.vocabulary.opportunity_units.yml
  config/sync/user.role.opportunity_editor.yml
Labels: size/s

#894 D8CORE-7661: Filtered List Paragraph
  config/sync/core.entity_form_display.paragraph.stanford_filtered_lists.default.yml
  config/sync/core.entity_view_display.paragraph.stanford_filtered_lists.default.yml
  config/sync/field.field.node.stanford_page.su_page_components.yml
  config/sync/field.field.paragraph.stanford_filtered_lists.su_filtered_list_view.yml
  config/sync/field.field.paragraph.stanford_filtered_lists.su_list_description.yml
  config/sync/field.field.paragraph.stanford_filtered_lists.su_list_headline.yml
  config/sync/field.storage.paragraph.su_filtered_list_view.yml
  config/sync/paragraphs.paragraphs_type.stanford_filtered_lists.yml
  config/sync/views.view.stanford_opportunities_filtered.yml
Labels: patch, size/m

#897 D8CORE:7898 - Reorganize the opportunity node layout
  config/sync/core.entity_view_display.node.stanford_opportunity.default.yml
Labels: size/s
