Repository SU-SWS/stanford_profile, pull requests merged in 2025-01, with the labels that each got.

#838 Remove obsolete module block_content_permissions
  composer.json
  config/sync/core.extension.yml
  config/sync/user.role.site_builder.yml
  config/sync/user.role.site_developer.yml
  config/sync/user.role.site_manager.yml
  config/sync/views.view.su_block_edit_links.yml
Labels: size/xs

#839 Fix tests with profile helper module dev
  composer.json
  tests/codeception/acceptance/Content/PublicationsCest.php
  tests/codeception/functional/Paragraphs/EntityReferenceCest.php
Labels: size/xs

#841 Updated editora11y module config
  config/sync/editoria11y.settings.yml
  tests/codeception/acceptance/Content/SearchBlockCest.php
  tests/codeception/acceptance/SystemSiteConfigCest.php
  tests/codeception/functional/Contrib/RedirectImportCest.php
  tests/codeception/functional/Navigation/NavigationDropDownsCest.php
Labels: size/xs

#840 D8CORE-7678: removed the medium and small quote
  config/sync/editor.editor.stanford_html.yml
Labels: size/xs

#835 Add and configure trash module for soft deleteing content
  composer.json
  config/sync/core.extension.yml
  config/sync/trash.settings.yml
  config/sync/ultimate_cron.job.trash_cron.yml
Labels: size/xs

#842 D8CORE-7532: removed wysiwyg p line length
  themes/stanford_basic/dist/css/components.css
  themes/stanford_basic/src/scss/components/wysiwyg/_line_length.scss
Labels: size/xs

#844 D8CORE-7703: fixed bad link, updated text
  config/sync/field.field.config_pages.lockup_settings.su_intro.yml
Labels: size/xs

#843 D8CORE-7531: removed max-width
  themes/stanford_basic/dist/css/ckeditor5.css
  themes/stanford_basic/src/scss/ckeditor5.scss
Labels: size/xs

#851 Revert "Add and configure trash module for soft deleteing content (#835)"
  composer.json
  config/sync/core.extension.yml
  config/sync/trash.settings.yml
  config/sync/ultimate_cron.job.trash_cron.yml
Labels: size/xs

#846 D8Core-7339: added help text to social links in footer.
  config/sync/core.entity_view_display.node.stanford_policy.printable.yml
  config/sync/editor.editor.stanford_html.yml
  config/sync/field.field.config_pages.stanford_local_footer.su_local_foot_social.yml
  config/sync/field_validation.rule_set.config_pages_stanford_local_footer.yml
  tests/codeception/acceptance/LocalFooter/LocalFooterCest.php
  themes/stanford_basic/dist/css/components.css
  themes/stanford_basic/src/scss/components/local-footer/_local-footer.scss
Labels: size/s

#847 D8CORE-7220: h1 on Homepage
  themes/stanford_basic/stanford_basic.theme
  themes/stanford_basic/templates/page--front.html.twig
Labels: size/xs

#856 D8CORE-7644: Updated user mail
  config/sync/user.mail.yml
Labels: size/xs

#859 D8CORE-7339: added net to the config validation
  config/sync/field_validation.rule_set.config_pages_stanford_local_footer.yml
Labels: size/xs

#855 D8CORE-7622: Site Reviewer Role
  config/sync/samlauth.authentication.yml
  config/sync/system.action.user_add_role_action.site_reviewer.yml
  config/sync/system.action.user_remove_role_action.site_reviewer.yml
  config/sync/user.role.site_reviewer.yml
  tests/codeception/acceptance/Users/RolesCest.php
Labels: size/xs

#858 D8CORE-7780: Content Management
  config/sync/views.view.manage_content.yml
Labels: size/xl

#862 Update field.field.config_pages.lockup_settings.su_intro.yml
  config/sync/field.field.config_pages.lockup_settings.su_intro.yml
Labels: size/xs

#863 D8CORE 7753 refactor accordion
  tests/codeception/functional/Paragraphs/AccordionCest.php
  themes/stanford_basic/dist/js/behaviors.js
  themes/stanford_basic/package.json
  themes/stanford_basic/src/js/stanford_basic.behavior.js
  themes/stanford_basic/yarn.lock
Labels: size/m

#865 11.5.1
  CHANGELOG.md
  composer.json
  stanford_profile.info.yml
Labels: patch, size/xs

#866 11.5.2
  CHANGELOG.md
  config/sync/user.role.anonymous.yml
  config/sync/user.role.authenticated.yml
  stanford_profile.info.yml
Labels: patch, size/xs
