Repository SU-SWS/stanford_profile, pull requests merged in 2025-05, with the labels that each got.

#919 D8CORE-8024 Fix order of decoupled menu items
  tests/codeception/functional/Navigation/DecoupledMenuCest.php
  themes/stanford_basic/decoupled-menu/dist/islands/main-menu.island.umd.js
  themes/stanford_basic/decoupled-menu/package.json
  themes/stanford_basic/decoupled-menu/src/main-menu.island.tsx
  themes/stanford_basic/decoupled-menu/yarn.lock
  themes/stanford_basic/stanford_basic.theme
Labels: size/l

#921 D8CORE-8029: made the contact email a link
  config/sync/core.entity_view_display.node.stanford_opportunity.default.yml
Labels: size/xs

#925 Add mysql57 module
  composer.json
  config/sync/core.extension.yml
Labels: size/xs

#923 D8CORE-8033: Added contextual filter
  config/sync/views.view.stanford_opportunities_filtered.yml
Labels: size/xs

#929 D8CORE-6470: Update Event Importer help text
  config/sync/field.field.config_pages.stanford_events_importer.su_localist_bookmark.yml
Labels: size/xs

#927 D8CORE-8047: Manage Basic Pages content management view
  config/sync/views.view.manage_content.yml
Labels: patch, size/m

#928 D8CORE-7836: Improved Events content management
  config/sync/views.view.manage_content.yml
Labels: size/s

#931 D8CORE-7736: Add unpublished site banner to all pages
  composer.json
  config/sync/block.block.minimally_branded_subtheme_unpublished_site.yml
  config/sync/block.block.stanford_basic_unpublished_site.yml
  config/sync/core.extension.yml
  config/sync/simple_block.simple_block.su_unpublished_site_banner.yml
  stanford_profile.post_update.php
  tests/codeception/acceptance/SystemSiteConfigCest.php
  tests/codeception/functional/Contrib/ExtLinkCest.php
Labels: size/s

#932 D8CORE-7843 D8CORE-8086 Add stat card and section background color options
  composer.json
  config/sync/block.block.minimally_branded_subtheme_unpublished_site.yml
  config/sync/core.entity_form_display.paragraph.stanford_layout.default.yml
  config/sync/core.entity_form_display.paragraph.stanford_stat_card.default.yml
  config/sync/core.entity_view_display.paragraph.stanford_layout.default.yml
  config/sync/core.entity_view_display.paragraph.stanford_stat_card.default.yml
  config/sync/core.extension.yml
  config/sync/field.field.node.stanford_page.su_page_components.yml
  config/sync/field.field.paragraph.stanford_stat_card.su_stat_bg_color.yml
  config/sync/field.field.paragraph.stanford_stat_card.su_stat_body.yml
  config/sync/field.field.paragraph.stanford_stat_card.su_stat_button.yml
  config/sync/field.field.paragraph.stanford_stat_card.su_stat_centered.yml
  config/sync/field.field.paragraph.stanford_stat_card.su_stat_headline.yml
  config/sync/field.field.paragraph.stanford_stat_card.su_stat_icon.yml
  config/sync/field.field.paragraph.stanford_stat_card.su_stat_icon_color.yml
  config/sync/field.field.paragraph.stanford_stat_card.su_stat_image.yml
  config/sync/field.field.paragraph.stanford_stat_card.su_stat_link_style.yml
  config/sync/field.field.paragraph.stanford_stat_card.su_stat_stat.yml
  config/sync/field.field.paragraph.stanford_stat_card.su_stat_stat_color.yml
  config/sync/field.field.paragraph.stanford_stat_card.su_stat_superhead.yml
  config/sync/field.storage.paragraph.su_stat_bg_color.yml
  config/sync/field.storage.paragraph.su_stat_body.yml
  config/sync/field.storage.paragraph.su_stat_button.yml
  config/sync/field.storage.paragraph.su_stat_centered.yml
  config/sync/field.storage.paragraph.su_stat_headline.yml
  config/sync/field.storage.paragraph.su_stat_icon.yml
  config/sync/field.storage.paragraph.su_stat_icon_color.yml
  config/sync/field.storage.paragraph.su_stat_image.yml
  config/sync/field.storage.paragraph.su_stat_link_style.yml
  config/sync/field.storage.paragraph.su_stat_stat.yml
  config/sync/field.storage.paragraph.su_stat_stat_color.yml
  config/sync/field.storage.paragraph.su_stat_superhead.yml
  config/sync/graphql_compose.settings.yml
  config/sync/paragraphs.paragraphs_type.stanford_stat_card.yml
  tests/codeception/acceptance/Content/BasicPageCest.php
  tests/codeception/acceptance/Paragraphs/StanfordStatCardCest.php
  themes/stanford_basic/dist/css/components.css
  themes/stanford_basic/package.json
  themes/stanford_basic/src/scss/components/all/_vertical-spacing.scss
  themes/stanford_basic/tests/behat/features/brandbar.feature
  themes/stanford_basic/tests/behat/features/globalfooter.feature
  themes/stanford_basic/tests/behat/features/lockup.feature
Labels: size/l
